# -*- coding: utf-8 -*-
"""
nexus_lang.py - Sprachen fuer NEXUS CEO (Deutsch, English, Türkçe)

Diese Datei liegt neben nexus_ceo.py. Der Bot uebersetzt jede Telegram-Nachricht erst beim
Senden: translate(text, sprache). Die Handelslogik arbeitet weiter mit den Originaltexten.
Fehlt diese Datei oder ist BOT_LANGUAGE nicht gesetzt, sendet der Bot die Originaltexte.

Aufbau:
  RULES     Liste (Quelltext-Vorlage, Deutsch, English, Türkçe). {0}, {1}, ... sind Platzhalter
            fuer Zahlen, Symbole usw. - sie muessen in jeder Sprache gleich oft vorkommen.
  UI        Texte fuer die Sprachwahl
  COMMANDS  Befehle: Hauptname im Code, weitere Namen, Beschreibung je Sprache
  BUTTONS   Beschriftung der Tasten je Sprache (das Emoji am Anfang muss bleiben)
  AI_HINT   Zusatz fuer die KI-Anfragen, damit die KI in der gewaehlten Sprache antwortet

Eine Uebersetzung verbessern: den Text in RULES aendern, Datei speichern, Bot neu starten.
Pruefen:  python3 nexus_lang.py          (Platzhalter aller Regeln)
          python3 nexus_lang.py de "Açık pozisyon yok."   (einen Text uebersetzen)
"""
import os
import re
import sys

LANGS = ("de", "en", "tr")
LANG_NAMES = {"de": "Deutsch", "en": "English", "tr": "Türkçe"}

# ---------------------------------------------------------------------------
# Sprachwahl
# ---------------------------------------------------------------------------
UI = {
    "choose": "🌐 Sprache wählen · Choose your language · Dil seçin",
    "confirm": {
        "de": "Sprache: Deutsch\n\nAlle Nachrichten und Befehle kommen dann auf Deutsch. Ist das richtig?",
        "en": "Language: English\n\nAll messages and commands will be in English. Is that correct?",
        "tr": "Dil: Türkçe\n\nTüm mesajlar ve komutlar Türkçe olacak. Doğru mu?",
    },
    "yes": {"de": "✅ Bestätigen", "en": "✅ Confirm", "tr": "✅ Onayla"},
    "back": {"de": "↩️ Zurück", "en": "↩️ Back", "tr": "↩️ Geri"},
    "saved": {
        "de": "✅ Sprache gespeichert: Deutsch\nIn der .env steht jetzt BOT_LANGUAGE=de. Ändern mit /sprache, Befehle mit /hilfe.",
        "en": "✅ Language saved: English\nThe .env now contains BOT_LANGUAGE=en. Change it with /language, list commands with /help.",
        "tr": "✅ Dil kaydedildi: Türkçe\n.env dosyasında artık BOT_LANGUAGE=tr yazıyor. Değiştirmek için /dil, komutlar için /yardim.",
    },
    "not_saved": {
        "de": "⚠️ Sprache für diese Sitzung gesetzt: Deutsch\nDie .env konnte nicht geschrieben werden ({0}). Bitte dort BOT_LANGUAGE=de eintragen.",
        "en": "⚠️ Language set for this session: English\nCould not write the .env ({0}). Please add BOT_LANGUAGE=en there.",
        "tr": "⚠️ Dil bu oturum için ayarlandı: Türkçe\n.env dosyasına yazılamadı ({0}). Lütfen oraya BOT_LANGUAGE=tr ekle.",
    },
    "keyboard": {"de": "⌨️ Tasten sind auf Deutsch.", "en": "⌨️ Buttons are in English.", "tr": "⌨️ Tuşlar Türkçe."},
}

# ---------------------------------------------------------------------------
# Befehle: Hauptname (so heisst der Befehl im Code) -> weitere Namen + Beschreibung
# Jeder Name funktioniert in jeder Sprache. "menu" = Name, der im Telegram-Menue der Sprache steht.
# ---------------------------------------------------------------------------
COMMANDS = {
    "pozisyon":      {"alias": ["position", "positionen", "positions"],
                      "menu": {"de": "position", "en": "position", "tr": "pozisyon"},
                      "desc": {"de": "Offene Positionen mit Stop, Ziel, Stufen", "en": "Open positions with stop, target, levels", "tr": "Açık pozisyonlar: stop, hedef, kademeler"}},
    "status":        {"alias": ["durum"],
                      "menu": {"de": "status", "en": "status", "tr": "status"},
                      "desc": {"de": "Volle KI-Analyse + Gremium", "en": "Full AI analysis + committee vote", "tr": "Tam yapay zekâ analizi + Kurul oylaması"}},
    "kapat":         {"alias": ["schliessen", "close"],
                      "menu": {"de": "schliessen", "en": "close", "tr": "kapat"},
                      "desc": {"de": "Schließen: /schliessen GOLD | /schliessen ALLE", "en": "Close: /close GOLD | /close ALL", "tr": "Kapat: /kapat GOLD | /kapat HEPSI"}},
    "manuell":       {"alias": ["manual", "manuel"],
                      "menu": {"de": "manuell", "en": "manual", "tr": "manuel"},
                      "desc": {"de": "Manueller Trade: /manuell GOLD BUY 100", "en": "Manual trade: /manual GOLD BUY 100", "tr": "Manuel işlem: /manuel GOLD BUY 100"}},
    "sl_weiten":     {"alias": ["sl_widen", "sl_genislet"],
                      "menu": {"de": "sl_weiten", "en": "sl_widen", "tr": "sl_genislet"},
                      "desc": {"de": "Stops im Tagesrauschen zeigen / weiten", "en": "Show / widen stops inside daily noise", "tr": "Günlük gürültüdeki stopları göster / genişlet"}},
    "ma":            {"alias": ["signale", "signals", "sinyaller"],
                      "menu": {"de": "signale", "en": "signals", "tr": "sinyaller"},
                      "desc": {"de": "Signale: MA 9/26 + ADX + RSI", "en": "Signals: MA 9/26 + ADX + RSI", "tr": "Sinyaller: MA 9/26 + ADX + RSI"}},
    "stats":         {"alias": ["statistik", "istatistik"],
                      "menu": {"de": "stats", "en": "stats", "tr": "stats"},
                      "desc": {"de": "Trade-Statistik je Asset", "en": "Trade statistics per asset", "tr": "Asset başına işlem istatistiği"}},
    "kayip":         {"alias": ["verluste", "losses"],
                      "menu": {"de": "verluste", "en": "losses", "tr": "kayip"},
                      "desc": {"de": "Verlustzähler von heute", "en": "Today's loss counter", "tr": "Bugünün kayıp sayacı"}},
    "bloklar":       {"alias": ["sperren", "blocks"],
                      "menu": {"de": "sperren", "en": "blocks", "tr": "bloklar"},
                      "desc": {"de": "Aktive Handelssperren", "en": "Active trading blocks", "tr": "Aktif HARD BLOCK listesi"}},
    "volatilite":    {"alias": ["volatilitaet", "volatility"],
                      "menu": {"de": "volatilitaet", "en": "volatility", "tr": "volatilite"},
                      "desc": {"de": "Schwarzer-Schwan-Prüfung jetzt", "en": "Run the Black Swan check now", "tr": "Volatilite + Kara Kuğu kontrolü"}},
    "update_models": {"alias": [],
                      "menu": {"de": "update_models", "en": "update_models", "tr": "update_models"},
                      "desc": {"de": "Gemini-Modelle und abgelehnte Keys", "en": "Gemini models and rejected keys", "tr": "Gemini modelleri ve reddedilen key'ler"}},
    "backtest":      {"alias": [],
                      "menu": {"de": "backtest", "en": "backtest", "tr": "backtest"},
                      "desc": {"de": "Backtest: /backtest GOLD 200", "en": "Backtest: /backtest GOLD 200", "tr": "Backtest: /backtest GOLD 200"}},
    "deepdive":      {"alias": [],
                      "menu": {"de": "deepdive", "en": "deepdive", "tr": "deepdive"},
                      "desc": {"de": "Detailanalyse: /deepdive GOLD HOUR_4 30", "en": "Deep dive: /deepdive GOLD HOUR_4 30", "tr": "Derin analiz: /deepdive GOLD HOUR_4 30"}},
    "news":          {"alias": ["nachrichten", "haberler"],
                      "menu": {"de": "nachrichten", "en": "news", "tr": "haberler"},
                      "desc": {"de": "Nachrichten: /nachrichten OIL 7", "en": "News: /news OIL 7", "tr": "Haberler: /haberler OIL 7"}},
    "newscollect":   {"alias": ["news_sammeln", "haber_topla"],
                      "menu": {"de": "news_sammeln", "en": "newscollect", "tr": "haber_topla"},
                      "desc": {"de": "Nachrichten jetzt sammeln", "en": "Collect news now", "tr": "Haberleri şimdi topla"}},
    "sources":       {"alias": ["quellen", "kaynaklar"],
                      "menu": {"de": "quellen", "en": "sources", "tr": "kaynaklar"},
                      "desc": {"de": "Zuverlässigkeit der Quellen", "en": "Source reliability scores", "tr": "Kaynak güvenilirlik skorları"}},
    "spread":        {"alias": [],
                      "menu": {"de": "spread", "en": "spread", "tr": "spread"},
                      "desc": {"de": "Spreads messen und speichern", "en": "Measure and store spreads", "tr": "Spread tarama + config güncelleme"}},
    "dbtemizle":     {"alias": ["db_bereinigen", "db_clean"],
                      "menu": {"de": "db_bereinigen", "en": "db_clean", "tr": "dbtemizle"},
                      "desc": {"de": "Alte Nachrichten aus der DB löschen", "en": "Delete old news from the DB", "tr": "Eski haberleri DB'den sil"}},
    "unut":          {"alias": ["vergessen", "forget"],
                      "menu": {"de": "vergessen", "en": "forget", "tr": "unut"},
                      "desc": {"de": "Gespeicherte Notizen löschen", "en": "Delete saved notes", "tr": "Kaydedilen notları sil"}},
    "diagnose":      {"alias": ["diagnosis", "teshis"],
                      "menu": {"de": "diagnose", "en": "diagnosis", "tr": "teshis"},
                      "desc": {"de": "Diagnose-Bericht: /diagnose oder /diagnose 3 (Tage)", "en": "Diagnosis report: /diagnosis or /diagnosis 3 (days)",
                               "tr": "Teşhis raporu: /teshis veya /teshis 3 (gün)"}},
    "sprache":       {"alias": ["language", "dil"],
                      "menu": {"de": "sprache", "en": "language", "tr": "dil"},
                      "desc": {"de": "Sprache ändern", "en": "Change language", "tr": "Dili değiştir"}},
    "help":          {"alias": ["hilfe", "yardim"],
                      "menu": {"de": "hilfe", "en": "help", "tr": "yardim"},
                      "desc": {"de": "Alle Befehle", "en": "All commands", "tr": "Tüm komutlar"}},
}

# Worte, die nach einem Befehl stehen duerfen (z.B. /close ALL CONFIRM)
WORDS_ALL = ("ALLE", "ALL", "HEPSI", "HEPSİ")
WORDS_CONFIRM = ("ONAYLA", "CONFIRM", "BESTAETIGEN", "BESTÄTIGEN")

# Tasten unter dem Eingabefeld. Das Emoji am Anfang erkennt der Bot - es muss bleiben.
BUTTONS = {
    "de": [["📍 Positionen", "📊 Status"], ["📈 Signale", "📰 Nachrichten"], ["🧮 Statistik", "💸 Verluste"], ["🔒 Sperren", "📋 Menü"], ["🔎 Diagnose"]],
    "en": [["📍 Positions", "📊 Status"], ["📈 Signals", "📰 News"], ["🧮 Stats", "💸 Losses"], ["🔒 Blocks", "📋 Menu"], ["🔎 Diagnosis"]],
    "tr": [["📍 Pozisyon", "📊 Status"], ["📈 Sinyaller", "📰 Haberler"], ["🧮 Stats", "💸 Kayip"], ["🔒 Bloklar", "📋 Menü"], ["🔎 Teşhis"]],
}

# Zusatz fuer die KI, damit sie in der gewaehlten Sprache schreibt. Alles Maschinenlesbare bleibt.
AI_HINT = {
    "de": ("\n\nSPRACHE: Schreibe alle erklärenden Texte auf Deutsch. Unverändert bleiben: Zeilen im Format "
           "'TRADE: ...' und 'ISLEM YOK: ...', alle DB_-Befehle (DB_WRITE, DB_NOTE, DB_FETCH ...), "
           "die Wörter BUY, SELL, KAPAT, TUT, HEDGE, Symbolnamen und Zahlen."),
    "en": ("\n\nLANGUAGE: Write all explanatory text in English. Keep unchanged: lines in the format "
           "'TRADE: ...' and 'ISLEM YOK: ...', all DB_ commands (DB_WRITE, DB_NOTE, DB_FETCH ...), "
           "the words BUY, SELL, KAPAT, TUT, HEDGE, symbol names and numbers."),
    "tr": ("\n\nDİL: Tüm açıklamaları Türkçe yaz. Aynen kalır: 'TRADE: ...' ve 'ISLEM YOK: ...' biçimindeki "
           "satırlar, tüm DB_ komutları (DB_WRITE, DB_NOTE, DB_FETCH ...), BUY, SELL, KAPAT, TUT, HEDGE "
           "kelimeleri, sembol adları ve sayılar."),
}


def command_names(main):
    """Alle Namen eines Befehls (Hauptname zuerst)."""
    c = COMMANDS.get(main)
    return [main] + [a for a in (c["alias"] if c else []) if a != main]


def menu_commands(lang):
    """[(name, beschreibung), ...] fuer das Telegram-Menue der Sprache."""
    return [(c["menu"].get(lang, main), c["desc"].get(lang, main)) for main, c in COMMANDS.items()]


def ai_hint(lang):
    return AI_HINT.get(lang, "")


# ---------------------------------------------------------------------------
# RULES: (Quelltext-Vorlage, Deutsch, English, Türkçe)
# ---------------------------------------------------------------------------
RULES = [
    ("🤖 NEXUS NATURE v15.6 — Komut Rehberi\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n📊 ANALİZ & DURUM\n/status      | status      — Tam Gemini analizi + Gremium oylama\n/pozisyon    | pozisyon    — Acik pozisyonlar, PnL, Pyramiding\n/sl_weiten                — Stops offener Positionen an der Tagesspanne pruefen (ausfuehren: /sl_weiten ja)\n/ma          | ma          — MA9/26 + ADX + RSI sinyalleri\n/stats       | stats       — Trade istatistikleri + asset performansi\n\n🔬 ARASTIRMA\n/backtest SEMBOL GUN      — Ornek: /backtest GOLD 200\n/deepdive SEMBOL TF GUN   — Ornek: /deepdive GOLD HOUR_4 30\n/news SEMBOL GUN          — Ornek: /news OIL 7\n/newscollect | newscollect — Manuel haber toplama: RSS + Grounding\n/sources     | sources     — Kaynak guvenilirlik skorlari\n/dbtemizle   | dbtemizle   — Eski/bozuk haberleri DB'den sil\n\n⚠️ RİSK & KONTROL\n/volatilite  | volatilite  — Volatilite + Kara Kugu kontrolu\n/spread      | spread      — Spread tarama + config guncelleme\n/kayip       | kayip       — Bugunun kayip/zarar sayaci\n/bloklar     | bloklar     — Aktif HARD BLOCK listesi\n\n💼 POZİSYON YÖNETİMİ\n/kapat SEMBOL             — Ornek: /kapat GOLD\n/kapat ALLE               — Tum pozisyonlari kapat (onay ister)\n/manuell SEMBOL YON SIZE  — Ornek: /manuell GOLD BUY 100\n  (opsiyonel: SL TP)      — Ornek: /manuell GOLD BUY 100 1900 2100\n\n🧠 HAFIZA\n/unut        | unut        — Kaydedilen kullanici notlarini sil\n\n💬 NOT GONDERME (quota YOK)\nKomut olmadan yaz = NOT olarak kaydedilir\nGemini 30 dk icinde kullanir (48 saat gecerli)\nOrnek: Iran rafinerileri kapaniyor, Brent yukselir\n\n🚫 HARD BLOCK\nAninda Python seviyesinde — Gemini override EDEMEZ!\n  'Silver satma'          → SILVER SELL blok\n  'Silver alma'           → SILVER BUY blok\n  'Gold nicht handeln'    → GOLD tam blok\n  'Silver serbest'        → SILVER blok kaldirilir\n\n/help        | help        — Bu menü",
     '🤖 NEXUS – Befehle\n━━━━━━━━━━━━━━━━━━━━━━\n\n📊 STAND & ANALYSE\n/position — offene Positionen mit Stop, Ziel, Tagesspanne, Stufen\n/status — volle KI-Analyse + Gremium (verbraucht eine Gemini-Anfrage)\n/signale — MA 9/26 + ADX + RSI\n/stats — Trade-Statistik je Asset\n/verluste — Verlustzähler von heute\n/sperren — aktive Handelssperren\n/volatilitaet — Schwarzer-Schwan-Prüfung jetzt\n/update_models — Gemini-Modelle und abgelehnte Keys\n/diagnose — Diagnose-Bericht der letzten 7 Tage (/diagnose 3 = 3 Tage)\n\n💼 POSITIONEN\n/schliessen GOLD — alle Positionen eines Symbols schließen\n/schliessen ALLE — alle Positionen schließen (fragt nach)\n/manuell GOLD BUY 100 — manueller Trade über 100 EUR\n/manuell GOLD BUY 100 1900 2100 — mit eigenem SL und TP\n/sl_weiten — Stops im Tagesrauschen zeigen (ausführen: /sl_weiten ja)\n\n🔬 RECHERCHE\n/backtest GOLD 200\n/deepdive GOLD HOUR_4 30\n/nachrichten OIL 7\n/news_sammeln — Nachrichten jetzt sammeln\n/quellen — Zuverlässigkeit der Quellen\n/spread — Spreads messen und speichern\n/db_bereinigen — alte Nachrichten löschen\n\n🧠 NOTIZEN\nText ohne Befehl = Notiz für die KI-Analyse (48 Stunden gültig)\n/vergessen — gespeicherte Notizen löschen\n\n🚫 HANDELSSPERRE PER TEXT\nDerzeit ohne Funktion (Fehler im Code, siehe Handbuch, Abschnitt 15).\nZum Stoppen: /schliessen und den Dienst anhalten.\n\n🌐 /sprache — Sprache ändern\n/hilfe — diese Übersicht',
     "🤖 NEXUS – Commands\n━━━━━━━━━━━━━━━━━━━━━━\n\n📊 STATUS & ANALYSIS\n/position — open positions with stop, target, daily range, levels\n/status — full AI analysis + committee vote (uses one Gemini request)\n/signals — MA 9/26 + ADX + RSI\n/stats — trade statistics per asset\n/losses — today's loss counter\n/blocks — active trading blocks\n/volatility — run the Black Swan check now\n/update_models — Gemini models and rejected keys\n/diagnosis — diagnosis report for the last 7 days (/diagnosis 3 = 3 days)\n\n💼 POSITIONS\n/close GOLD — close all positions of one symbol\n/close ALL — close all positions (asks first)\n/manual GOLD BUY 100 — manual trade for 100 EUR\n/manual GOLD BUY 100 1900 2100 — with your own SL and TP\n/sl_widen — show stops inside the daily noise (apply: /sl_widen yes)\n\n🔬 RESEARCH\n/backtest GOLD 200\n/deepdive GOLD HOUR_4 30\n/news OIL 7\n/newscollect — collect news now\n/sources — source reliability scores\n/spread — measure and store spreads\n/db_clean — delete old news\n\n🧠 NOTES\nText without a command = note for the AI analysis (valid 48 hours)\n/forget — delete saved notes\n\n🚫 TRADING BLOCK BY TEXT\nCurrently not working (bug in the code, see manual, section 15).\nTo stop trading: /close and stop the service.\n\n🌐 /language — change language\n/help — this overview",
     "🤖 NEXUS – Komutlar\n━━━━━━━━━━━━━━━━━━━━━━\n\n📊 DURUM & ANALİZ\n/pozisyon — açık pozisyonlar: stop, hedef, günlük aralık, kademeler\n/status — tam yapay zekâ analizi + Kurul oylaması (bir Gemini isteği harcar)\n/sinyaller — MA 9/26 + ADX + RSI\n/stats — asset başına işlem istatistiği\n/kayip — bugünün kayıp sayacı\n/bloklar — aktif HARD BLOCK listesi\n/volatilite — Kara Kuğu kontrolünü şimdi çalıştır\n/update_models — Gemini modelleri ve reddedilen key'ler\n/teshis — son 7 günün teşhis raporu (/teshis 3 = 3 gün)\n\n💼 POZİSYONLAR\n/kapat GOLD — bir sembolün tüm pozisyonlarını kapat\n/kapat HEPSI — tüm pozisyonları kapat (onay ister)\n/manuel GOLD BUY 100 — 100 EUR'luk manuel işlem\n/manuel GOLD BUY 100 1900 2100 — kendi SL ve TP değerinle\n/sl_genislet — günlük gürültüdeki stopları göster (uygula: /sl_genislet evet)\n\n🔬 ARAŞTIRMA\n/backtest GOLD 200\n/deepdive GOLD HOUR_4 30\n/haberler OIL 7\n/haber_topla — haberleri şimdi topla\n/kaynaklar — kaynak güvenilirlik skorları\n/spread — spread tarama + config güncelleme\n/dbtemizle — eski haberleri sil\n\n🧠 NOTLAR\nKomutsuz yazı = yapay zekâ analizi için not (48 saat geçerli)\n/unut — kaydedilen notları sil\n\n🚫 YAZIYLA HARD BLOCK\nŞu an çalışmıyor (koddaki hata, kılavuz bölüm 15).\nİşlemi durdurmak için: /kapat ve servisi durdur.\n\n🌐 /dil — dili değiştir\n/yardim — bu menü"),
    ('🕐 {0} | NEXUS NATURE {1} - BRIDGEWATER EDITION Baslatildi\nMod: Rogers Filter + Gremium 5 + MA/ADX/RSI/BB/FIB/EMA200\nInterval: {2}h (Macro-Scan) | Max Positionen: {3}\nKara Kuğu Koruması (3 Seviye):\n  -%8  Gemini Acil Karar\n  -%12 Otomatik Kapat\n  -%18 ACIL TUM POZİSYONLARI KAPAT\nKoruma-Thread: 5 Dakika (Quota yok)\nHaber-Thread: 60 Dakika (RSS + X/Nitter, Quota yok)\nAlternatif Veri: 31 Cargo Airline + 18 Gemi Bolgesi + BDI\n  GDACS + NHC Kasirga + HDD/CDD + AB Gaz Deposu + ECMWF + NOAA\nHaber Geçmişi: 14 Gün\nPyramiding: Sinir yok (min %2 kar per seviye) | EXIT: Gemini veya Trailing SL %5\nStop Loss: min. {4} × Tagesspanne (Tages-ATR), max. {5}% | /sl_weiten\nWiedereinstieg: frühestens {6} h nach einer Schließung | Scan-Meldungen: {7}\nGremium: Cihat/Rogers/Dalio/Taleb/Soros ({8}/5 JA gerekli, Krypto {9}/5)\nSpread Filter: Max {10} | Auto-Config: AKTİF\nHaftasonu: ALLE Assets AKTIF (Krypto gleich wie andere behandelt)\nAşama 1 Filtre (Bollinger+Fib): AKTİF\nGoogle Search Grounding: DEAKTIF (GDELT + AlphaVantage aktif)\nSQLite Hafıza: AKTİF\nKelly-Kriteri: AKTİF\nEconomic Calendar: AKTIF\nHava Durumu API: AKTİF\nKaynak Güvenilirliği: AKTİF\n\nKomutlar: /help\n\n🔧 TRADING ASSETS:\n{11}',
     '🕐 {0} | NEXUS {1} gestartet\nModus: Rogers-Filter + Gremium (5 Regeln) + MA/ADX/RSI/BB/FIB/EMA200\nScan-Intervall: {2} h | Max. Positionen: {3}\nSchwarzer-Schwan-Schutz (3 Stufen):\n  -8 %  KI-Notfallentscheidung\n  -12 % automatisch schließen\n  -18 % ALLE POSITIONEN SCHLIESSEN\nSchutz-Lauf: alle 5 Minuten (ohne KI-Kontingent)\nNachrichten: alle 60 Minuten (RSS + X, ohne KI-Kontingent)\nZusatzdaten: Frachtflüge, Schiffsverkehr, BDI, GDACS, Hurrikane, HDD/CDD, EU-Gasspeicher, Wetter\nNachrichten-Archiv: 14 Tage\nPyramiding: ohne Obergrenze (mind. 2 % Gewinn je Stufe) | Exit: KI oder Trailing-SL 5 %\nStop Loss: mind. {4} × Tagesspanne (Tages-ATR), max. {5}% | /sl_weiten\nWiedereinstieg: frühestens {6} h nach einer Schließung | Scan-Meldungen: {7}\nGremium: Cihat/Rogers/Dalio/Taleb/Soros ({8}/5 JA nötig, Krypto {9}/5)\nSpread-Filter: max. {10}\nWochenende: nur Krypto (höchstens 3 Positionen)\n\nBefehle: /hilfe | Sprache: /sprache\n\n🔧 HANDELBARE SYMBOLE:\n{11}',
     '🕐 {0} | NEXUS {1} started\nMode: Rogers filter + committee (5 rules) + MA/ADX/RSI/BB/FIB/EMA200\nScan interval: {2} h | Max positions: {3}\nBlack Swan protection (3 levels):\n  -8%  AI emergency decision\n  -12% close automatically\n  -18% CLOSE ALL POSITIONS\nProtection run: every 5 minutes (no AI quota)\nNews: every 60 minutes (RSS + X, no AI quota)\nExtra data: cargo flights, ship traffic, BDI, GDACS, hurricanes, HDD/CDD, EU gas storage, weather\nNews archive: 14 days\nPyramiding: no upper limit (min 2% profit per level) | Exit: AI or trailing SL 5%\nStop Loss: min {4} × daily range (daily ATR), max {5}% | /sl_widen\nRe-entry: earliest {6} h after a close | Scan messages: {7}\nCommittee: Cihat/Rogers/Dalio/Taleb/Soros ({8}/5 YES needed, crypto {9}/5)\nSpread filter: max {10}\nWeekend: crypto only (at most 3 positions)\n\nCommands: /help | Language: /language\n\n🔧 TRADABLE SYMBOLS:\n{11}',
     '🕐 {0} | NEXUS {1} başlatıldı\nMod: Rogers filtresi + Kurul (5 kural) + MA/ADX/RSI/BB/FIB/EMA200\nTarama aralığı: {2} sa | Maks. pozisyon: {3}\nKara Kuğu koruması (3 seviye):\n  -%8  yapay zekâ acil kararı\n  -%12 otomatik kapat\n  -%18 TÜM POZİSYONLARI KAPAT\nKoruma döngüsü: 5 dakikada bir (kota harcamaz)\nHaberler: 60 dakikada bir (RSS + X, kota harcamaz)\nEk veriler: kargo uçuşları, gemi trafiği, BDI, GDACS, kasırgalar, HDD/CDD, AB gaz depoları, hava durumu\nHaber arşivi: 14 gün\nPyramiding: üst sınır yok (seviye başına en az %2 kâr) | Çıkış: yapay zekâ veya Trailing SL %5\nStop Loss: en az {4} × günlük aralık (günlük ATR), en çok %{5} | /sl_genislet\nYeniden giriş: kapanıştan en erken {6} sa sonra | Tarama mesajları: {7}\nKurul: Cihat/Rogers/Dalio/Taleb/Soros ({8}/5 EVET gerekli, kripto {9}/5)\nSpread filtresi: maks. {10}\nHafta sonu: yalnızca kripto (en çok 3 pozisyon)\n\nKomutlar: /yardim | Dil: /dil\n\n🔧 İŞLEM YAPILAN SEMBOLLER:\n{11}'),
    ('⚠️ Invertierte Zinskurve {0}% → Rezession',
     '⚠️ Invertierte Zinskurve {0}% → Rezession',
     '⚠️ Inverted yield curve {0}% → recession',
     '⚠️ Ters getiri eğrisi %{0} → resesyon'),
    ('🚨 HY-Spread {0}%',
     '🚨 HY-Spread {0}%',
     '🚨 HY spread {0}%',
     '🚨 HY spread %{0}'),
    ('ATR={0}×{1}={2} ({3}%)',
     'ATR={0}×{1}={2} ({3}%)',
     'ATR={0}×{1}={2} ({3}%)',
     'ATR={0}×{1}={2} (%{3})'),
    ('Fallback 1.5% ({0})',
     'Fallback 1.5% ({0})',
     'Fallback 1.5% ({0})',
     'Fallback %1.5 ({0})'),
    ('fester Mindestabstand {0}%',
     'fester Mindestabstand {0}%',
     'fixed minimum distance {0}%',
     'sabit asgari mesafe %{0}'),
    ('Tagesspanne nicht abrufbar ({0}) - fester Mindestabstand {1}%',
     'Tagesspanne nicht abrufbar ({0}) - fester Mindestabstand {1}%',
     'daily range unavailable ({0}) - fixed minimum distance {1}%',
     'günlük aralık alınamadı ({0}) - sabit asgari mesafe %{1}'),
    ('{0} × Tagesspanne {1} wäre {2}% - begrenzt auf {3}% (SL_MAX_PCT)',
     '{0} × Tagesspanne {1} wäre {2}% - begrenzt auf {3}% (SL_MAX_PCT)',
     '{0} × daily range {1} would be {2}% - capped at {3}% (SL_MAX_PCT)',
     '{0} × günlük aralık {1} %{2} olurdu - %{3} ile sınırlandı (SL_MAX_PCT)'),
    ('fester Mindestabstand {0}% (Tagesspanne {1} ist kleiner)',
     'fester Mindestabstand {0}% (Tagesspanne {1} ist kleiner)',
     'fixed minimum distance {0}% (daily range {1} is smaller)',
     'sabit asgari mesafe %{0} (günlük aralık {1} daha küçük)'),
    ('{0} × Tagesspanne {1} = {2}%',
     '{0} × Tagesspanne {1} = {2}%',
     '{0} × daily range {1} = {2}%',
     '{0} × günlük aralık {1} = %{2}'),
    ('Einstieg/Richtung nicht lesbar - bleibt',
     'Einstieg/Richtung nicht lesbar - bleibt',
     'entry/direction not readable - kept',
     'giriş/yön okunamıyor - aynı kalıyor'),
    ('kein Stop gesetzt - bleibt unverändert',
     'kein Stop gesetzt - bleibt unverändert',
     'no stop set - left unchanged',
     'stop ayarlı değil - değişmeden kalıyor'),
    ('Stop {0} liegt am Einstieg oder im Gewinn - bleibt',
     'Stop {0} liegt am Einstieg oder im Gewinn - bleibt',
     'Stop {0} is at entry or in profit - kept',
     'Stop {0} girişte veya kârda - aynı kalıyor'),
    ('Stop {0} ({1}%) ist weit genug - bleibt',
     'Stop {0} ({1}%) ist weit genug - bleibt',
     'Stop {0} ({1}%) is wide enough - kept',
     'Stop {0} (%{1}) yeterince geniş - aynı kalıyor'),
    ('Stop {0} ({1}%) → {2} ({3}%) | {4} | Verlust am neuen Stop ca. {5} (Währung des Instruments)',
     'Stop {0} ({1}%) → {2} ({3}%) | {4} | Verlust am neuen Stop ca. {5} (Währung des Instruments)',
     'Stop {0} ({1}%) → {2} ({3}%) | {4} | loss at new stop approx. {5} (instrument currency)',
     "Stop {0} (%{1}) → {2} (%{3}) | {4} | yeni stop'ta kayıp yaklaşık {5} (enstrümanın para birimi)"),
    ('Günlük hedef: +{0}€ ✅',
     'Tagesziel: +{0}€ ✅',
     'Daily target: +{0}€ ✅',
     'Günlük hedef: +{0}€ ✅'),
    ('Maks kayıp: {0}€ 🛑',
     'Max. Verlust: {0}€ 🛑',
     'Max loss: {0}€ 🛑',
     'Maks kayıp: {0}€ 🛑'),
    ('Bugün PnL: {0}€',
     'PnL heute: {0}€',
     'PnL today: {0}€',
     'Bugün PnL: {0}€'),
    ('Limit check hata: {0}',
     'Fehler bei Limit-Prüfung: {0}',
     'Limit check error: {0}',
     'Limit check hata: {0}'),
    ('META-BLOCK: {0}: %{1} win_rate',
     'META-BLOCK: {0}: {1}% win_rate',
     'META-BLOCK: {0}: {1}% win_rate',
     'META-BLOCK: {0}: %{1} win_rate'),
    ('✅ {0}: %{1} → GÜÇLÜ',
     '✅ {0}: {1}% → STARK',
     '✅ {0}: {1}% → STRONG',
     '✅ {0}: %{1} → GÜÇLÜ'),
    ('Meta-Learn: {0} pattern, {1} önemli',
     'Meta-Learn: {0} Muster, {1} wichtig',
     'Meta-Learn: {0} patterns, {1} significant',
     'Meta-Learn: {0} pattern, {1} önemli'),
    ('🚨 NEXUS JOURNAL\n❌ Modul: {0}\nFehler: {1}\nZeit: {2}',
     '🚨 NEXUS JOURNAL\n❌ Modul: {0}\nFehler: {1}\nZeit: {2}',
     '🚨 NEXUS JOURNAL\n❌ Module: {0}\nError: {1}\nTime: {2}',
     '🚨 NEXUS JOURNAL\n❌ Modül: {0}\nHata: {1}\nZaman: {2}'),
    ('✅ NEXUS JOURNAL\n{0} wiederhergestellt',
     '✅ NEXUS JOURNAL\n{0} wiederhergestellt',
     '✅ NEXUS JOURNAL\n{0} restored',
     '✅ NEXUS JOURNAL\n{0} tekrar çalışıyor'),
    ('Aylık limit doldu ({0}/{1})',
     'Monatslimit erreicht ({0}/{1})',
     'Monthly limit reached ({0}/{1})',
     'Aylık limit doldu ({0}/{1})'),
    ('15 dakika limiti doldu ({0}/{1})',
     '15-Minuten-Limit erreicht ({0}/{1})',
     '15-minute limit reached ({0}/{1})',
     '15 dakika limiti doldu ({0}/{1})'),
    ('🔒 X API Güvenlik Kilidi: {0}\n✅ RSS ve bot çalışmaya devam ediyor.',
     '🔒 X API Sicherheitssperre: {0}\n✅ RSS und Bot laufen weiter.',
     '🔒 X API safety lock: {0}\n✅ RSS and bot keep running.',
     '🔒 X API Güvenlik Kilidi: {0}\n✅ RSS ve bot çalışmaya devam ediyor.'),
    ('Tageslimit erreicht',
     'Tageslimit erreicht',
     'daily limit reached',
     'günlük limit doldu'),
    ('kein Gratis-Kontingent / nicht verfügbar',
     'kein Gratis-Kontingent / nicht verfügbar',
     'no free quota / not available',
     'ücretsiz kota yok / kullanılamıyor'),
    ('Server überlastet (503)',
     'Server überlastet (503)',
     'server overloaded (503)',
     'sunucu aşırı yüklü (503)'),
    ('Key abgelehnt',
     'Key abgelehnt',
     'key rejected',
     'key reddedildi'),
    ('anderer Fehler',
     'anderer Fehler',
     'other error',
     'başka hata'),
    ('• Keys: nur {0} von {1} nutzbar - von Google abgelehnt (401): ',
     '• Keys: nur {0} von {1} nutzbar - von Google abgelehnt (401): ',
     '• Keys: only {0} of {1} usable - rejected by Google (401): ',
     "• Key'ler: {1} taneden sadece {0} tanesi kullanılabilir - Google tarafından reddedildi (401): "),
    (' ({0} Key{1}',
     ' ({0} Key{1}',
     ' ({0} key{1}',
     ' ({0} key{1}'),
    (', ruht bis {0}',
     ', ruht bis {0}',
     ', resting until {0}',
     ', şu saate kadar bekliyor: {0}'),
    ('Server überlastet (503, auch beim 2. Versuch)',
     'Server überlastet (503, auch beim 2. Versuch)',
     'server overloaded (503, also on 2nd attempt)',
     'sunucu aşırı yüklü (503, 2. denemede de)'),
    ('Tageslimit, ruht bis {0}',
     'Tageslimit, ruht bis {0}',
     'daily limit, resting until {0}',
     'günlük limit, şu saate kadar bekliyor: {0}'),
    ('nicht verfügbar, gesperrt bis {0}',
     'nicht verfügbar, gesperrt bis {0}',
     'not available, blocked until {0}',
     'kullanılamıyor, şu saate kadar engelli: {0}'),
    ('leere Antwort',
     'leere Antwort',
     'empty response',
     'boş yanıt'),
    ('Gemini: key yok',
     'Gemini: kein Key',
     'Gemini: no key',
     'Gemini: key yok'),
    ('🤖 GEMINI MODELL-KETTE',
     '🤖 GEMINI MODELL-KETTE',
     '🤖 GEMINI MODEL CHAIN',
     '🤖 GEMINI MODEL ZİNCİRİ'),
    ('keine (alles gesperrt/leer)',
     'keine (alles gesperrt/leer)',
     'none (all blocked/empty)',
     'yok (hepsi engelli/boş)'),
    ('Kette jetzt: ',
     'Kette jetzt: ',
     'Chain now: ',
     'Zincir şimdi: '),
    ('noch nicht abgerufen (Notfallliste aktiv)',
     'noch nicht abgerufen (Notfallliste aktiv)',
     'not fetched yet (emergency list active)',
     'henüz alınmadı (acil durum listesi aktif)'),
    ('Live-Liste: ',
     'Live-Liste: ',
     'Live list: ',
     'Canlı liste: '),
    ('{0} (bis {1})',
     '{0} (bis {1})',
     '{0} (until {1})',
     '{0} (şu saate kadar: {1})'),
    ('Tageskontingent leer: ',
     'Tageskontingent leer: ',
     'Daily quota exhausted: ',
     'Günlük kota tükendi: '),
    ('Gesperrt (kein Free-Tier / nicht vorhanden): ',
     'Gesperrt (kein Free-Tier / nicht vorhanden): ',
     'Blocked (no free tier / does not exist): ',
     'Engelli (ücretsiz katman yok / mevcut değil): '),
    ('Keys: nur {0} nutzbar - von Google abgelehnt (401): ',
     'Keys: nur {0} nutzbar - von Google abgelehnt (401): ',
     'Keys: only {0} usable - rejected by Google (401): ',
     "Key'ler: sadece {0} tanesi kullanılabilir - Google tarafından reddedildi (401): "),
    ('🤖 Gemini-Kette aktualisiert:\n{0}',
     '🤖 Gemini-Kette aktualisiert:\n{0}',
     '🤖 Gemini chain updated:\n{0}',
     '🤖 Gemini zinciri güncellendi:\n{0}'),
    ('⚠️ Ollama yanıt vermedi.',
     '⚠️ Ollama hat nicht geantwortet.',
     '⚠️ Ollama did not respond.',
     '⚠️ Ollama yanıt vermedi.'),
    ('⚠️ Tüm AI sağlayıcılar şu an kullanılamıyor. Lütfen daha sonra tekrar dene.',
     '⚠️ Alle KI-Anbieter sind gerade nicht verfügbar. Bitte versuch es später noch einmal.',
     '⚠️ All AI providers are currently unavailable. Please try again later.',
     '⚠️ Tüm AI sağlayıcılar şu an kullanılamıyor. Lütfen daha sonra tekrar dene.'),
    ('Henuz trade gecmisi yok.',
     'Noch keine Trade-Historie.',
     'No trade history yet.',
     'Henüz trade geçmişi yok.'),
    ('  ACIK {0} {1} | {2} | Gremium:{3}',
     '  OFFEN {0} {1} | {2} | Gremium:{3}',
     '  OPEN {0} {1} | {2} | Committee:{3}',
     '  AÇIK {0} {1} | {2} | Kurul:{3}'),
    ('  KAZANC {0} {1} | +{2}EUR | {3} | {4}',
     '  GEWINN {0} {1} | +{2}EUR | {3} | {4}',
     '  WIN {0} {1} | +{2}EUR | {3} | {4}',
     '  KAZANÇ {0} {1} | +{2}EUR | {3} | {4}'),
    ('Henuz asset istatistigi yok.',
     'Noch keine Asset-Statistik.',
     'No asset statistics yet.',
     'Henüz asset istatistiği yok.'),
    (' KAYIP SERISI!',
     ' VERLUSTSERIE!',
     ' LOSING STREAK!',
     ' KAYIP SERİSİ!'),
    ('  {0}: Win%={1} HaftasonuWin%={2} ({3}t) PnL:{4}EUR{5}',
     '  {0}: Win%={1} WochenendeWin%={2} ({3}t) PnL:{4}EUR{5}',
     '  {0}: Win%={1} WeekendWin%={2} ({3}t) PnL:{4}EUR{5}',
     '  {0}: Win%={1} HaftasonuWin%={2} ({3}t) PnL:{4}EUR{5}'),
    ('Henuz kaynak degerlendirmesi yok.',
     'Noch keine Quellenbewertung.',
     'No source ratings yet.',
     'Henüz kaynak değerlendirmesi yok.'),
    ('  [{0}] {1}: {2} ({3} kullanim)',
     '  [{0}] {1}: {2} ({3} Nutzungen)',
     '  [{0}] {1}: {2} ({3} uses)',
     '  [{0}] {1}: {2} ({3} kullanım)'),
    ('Asset:{0} Res:{1} Guncelleme:{2} ({3} mum)',
     'Asset:{0} Res:{1} Aktualisiert:{2} ({3} Kerzen)',
     'Asset:{0} Res:{1} Updated:{2} ({3} candles)',
     'Asset:{0} Res:{1} Güncelleme:{2} ({3} mum)'),
    ('Fiyat:{0} | 30-Mum Degisim:{1}%',
     'Kurs:{0} | 30-Kerzen-Änderung:{1}%',
     'Price:{0} | 30-candle change:{1}%',
     'Fiyat:{0} | 30-Mum Değişim:{1}%'),
    ('BB: Alt={0} Orta={1} Ust={2} Poz={3}',
     'BB: Unten={0} Mitte={1} Oben={2} Pos={3}',
     'BB: Lower={0} Mid={1} Upper={2} Pos={3}',
     'BB: Alt={0} Orta={1} Üst={2} Poz={3}'),
    ('FIB: 38.2%={0} 61.8%={1} YakinSev={2}@{3}%',
     'FIB: 38.2%={0} 61.8%={1} NaheStufe={2}@{3}%',
     'FIB: 38.2%={0} 61.8%={1} NearLevel={2}@{3}%',
     'FIB: 38.2%={0} 61.8%={1} YakınSev={2}@{3}%'),
    ('Veri yetersiz',
     'Zu wenige Daten',
     'Not enough data',
     'Veri yetersiz'),
    ('Sinyal yok',
     'Kein Signal',
     'No signal',
     'Sinyal yok'),
    ('NEXUS BACKTEST: {0} | {1} gün',
     'NEXUS BACKTEST: {0} | {1} Tage',
     'NEXUS BACKTEST: {0} | {1} days',
     'NEXUS BACKTEST: {0} | {1} gün'),
    ('  Sinyal:{0} | K/Z:{1}/{2}',
     '  Signale:{0} | G/V:{1}/{2}',
     '  Signals:{0} | W/L:{1}/{2}',
     '  Sinyal:{0} | K/Z:{1}/{2}'),
    ('  WinRate:{0} | AvgKazanc:{1}% | AvgKayip:{2}%',
     '  WinRate:{0} | AvgGewinn:{1}% | AvgVerlust:{2}%',
     '  WinRate:{0} | AvgWin:{1}% | AvgLoss:{2}%',
     '  WinRate:{0} | AvgKazanç:{1}% | AvgKayıp:{2}%'),
    ('  ToplamPnL:{0}% | MaxDD:-{1}%',
     '  GesamtPnL:{0}% | MaxDD:-{1}%',
     '  TotalPnL:{0}% | MaxDD:-{1}%',
     '  ToplamPnL:{0}% | MaxDD:-{1}%'),
    ('  >> GÜÇLÜ STRATEJİ',
     '  >> STARKE STRATEGIE',
     '  >> STRONG STRATEGY',
     '  >> GÜÇLÜ STRATEJİ'),
    ('  >> ORTA - iyileştirme gerekli',
     '  >> MITTEL - Verbesserung nötig',
     '  >> MEDIUM - improvement needed',
     '  >> ORTA - iyileştirme gerekli'),
    ('  >> ZAYIF - bu zaman dilimi dikkat!',
     '  >> SCHWACH - Vorsicht bei diesem Zeitraum!',
     '  >> WEAK - caution with this timeframe!',
     '  >> ZAYIF - bu zaman dilimi dikkat!'),
    ('\nDetaylar veritabanına kaydedildi.',
     '\nDetails in der Datenbank gespeichert.',
     '\nDetails saved to the database.',
     '\nDetaylar veritabanına kaydedildi.'),
    ('Veri yok',
     'Keine Daten',
     'No data',
     'Veri yok'),
    ('GDACS KRİTİK UYARI!\nTip: {0} | Büyüklük:{1}\nKonum: {2}\nEtkilenen Assetler: {3}',
     'GDACS KRITISCHE WARNUNG!\nTyp: {0} | Stärke:{1}\nOrt: {2}\nBetroffene Assets: {3}',
     'GDACS CRITICAL ALERT!\nType: {0} | Magnitude:{1}\nLocation: {2}\nAffected assets: {3}',
     'GDACS KRİTİK UYARI!\nTip: {0} | Büyüklük:{1}\nKonum: {2}\nEtkilenen Assetler: {3}'),
    ('Veri yetersiz (Rogers EMA200 icin min 205 mum)',
     'Zu wenige Daten (Rogers EMA200 braucht mind. 205 Kerzen)',
     'Not enough data (Rogers EMA200 needs min 205 candles)',
     'Veri yetersiz (Rogers EMA200 için min 205 mum)'),
    ('SMA20 verisi yetersiz',
     'Zu wenige SMA20-Daten',
     'Not enough SMA20 data',
     'SMA20 verisi yetersiz'),
    ('BB Bandwidth hesaplanamadı',
     'BB Bandwidth konnte nicht berechnet werden',
     'BB Bandwidth could not be calculated',
     'BB Bandwidth hesaplanamadı'),
    ('Rogers koşulları sağlanmadı: ',
     'Rogers-Bedingungen nicht erfüllt: ',
     'Rogers conditions not met: ',
     'Rogers koşulları sağlanmadı: '),
    ('API verisi alinamadi ({0})',
     'API-Daten nicht abrufbar ({0})',
     'API data could not be fetched ({0})',
     'API verisi alınamadı ({0})'),
    ('Veri yetersiz ({0} mum)',
     'Zu wenige Daten ({0} Kerzen)',
     'Not enough data ({0} candles)',
     'Veri yetersiz ({0} mum)'),
    ('MA:NOTR(0)',
     'MA:NEUTRAL(0)',
     'MA:NEUTRAL(0)',
     'MA:NÖTR(0)'),
    ('BB:NODATA(0)',
     'BB:KEINE DATEN(0)',
     'BB:NODATA(0)',
     'BB:VERİ YOK(0)'),
    ('FIB:NODATA(0)',
     'FIB:KEINE DATEN(0)',
     'FIB:NODATA(0)',
     'FIB:VERİ YOK(0)'),
    ('Veri yok ({0})',
     'Keine Daten ({0})',
     'No data ({0})',
     'Veri yok ({0})'),
    ('ROGERS:JA(+1)',
     'ROGERS:JA(+1)',
     'ROGERS:YES(+1)',
     'ROGERS:EVET(+1)'),
    ('ROGERS:NEIN(0)',
     'ROGERS:NEIN(0)',
     'ROGERS:NO(0)',
     'ROGERS:HAYIR(0)'),
    ('ROGERS:N/A(Kripto)',
     'ROGERS:N/A(Krypto)',
     'ROGERS:N/A(Crypto)',
     'ROGERS:N/A(Kripto)'),
    ('GUNLUK KAYIP ALARMI: Depo degeri %',
     'TAGESVERLUST-ALARM: Depotwert um %',
     'DAILY LOSS ALARM: account value %',
     'GÜNLÜK KAYIP ALARMI: Depo değeri %'),
    (' dustu! Peak: ',
     ' gefallen! Peak: ',
     ' down! Peak: ',
     ' düştü! Peak: '),
    ('EUR Simdi: ',
     'EUR Jetzt: ',
     'EUR Now: ',
     'EUR Şimdi: '),
    ('EUR Kayip: ',
     'EUR Verlust: ',
     'EUR Loss: ',
     'EUR Kayıp: '),
    ('%) BUGUN YENİ TRADE YOK!',
     '%) HEUTE KEINE NEUEN TRADES!',
     '%) NO NEW TRADES TODAY!',
     '%) BUGÜN YENİ TRADE YOK!'),
    ('GUNLUK KAYIP ALARMI: EUR kayip limiti asildi! Peak: ',
     'TAGESVERLUST-ALARM: EUR-Verlustlimit überschritten! Peak: ',
     'DAILY LOSS ALERT: EUR loss limit exceeded! Peak: ',
     'GÜNLÜK KAYIP ALARMI: EUR kayıp limiti aşıldı! Peak: '),
    ('EUR BUGUN YENİ TRADE YOK!',
     'EUR HEUTE KEINE NEUEN TRADES!',
     'EUR NO NEW TRADES TODAY!',
     'EUR BUGÜN YENİ TRADE YOK!'),
    ('Pyramiding-Sync: Session nicht bereit ({0})',
     'Pyramiding-Sync: Session nicht bereit ({0})',
     'Pyramiding sync: session not ready ({0})',
     'Pyramiding-Senkron: oturum hazır değil ({0})'),
    ('Piramiding-Senkron: API bağlantısı yok',
     'Pyramiding-Sync: keine API-Verbindung',
     'Pyramiding sync: no API connection',
     'Piramiding-Senkron: API bağlantısı yok'),
    ('Pyramiding-Sync Fehler: {0}',
     'Pyramiding-Sync Fehler: {0}',
     'Pyramiding sync error: {0}',
     'Pyramiding-Senkron hatası: {0}'),
    ('  {0}: {1} -> {2} (düzeltildi)',
     '  {0}: {1} -> {2} (korrigiert)',
     '  {0}: {1} -> {2} (corrected)',
     '  {0}: {1} -> {2} (düzeltildi)'),
    ('  {0}: {1} -> 0 (kapatıldı)',
     '  {0}: {1} -> 0 (geschlossen)',
     '  {0}: {1} -> 0 (closed)',
     '  {0}: {1} -> 0 (kapatıldı)'),
    ('Pyramiding-Sync korrigiert:\n',
     'Pyramiding-Sync korrigiert:\n',
     'Pyramiding sync corrected:\n',
     'Pyramiding-Senkron düzeltildi:\n'),
    ('Pyramiding-Sync: {0} Epics korrekt',
     'Pyramiding-Sync: {0} Epics korrekt',
     'Pyramiding sync: {0} epics correct',
     'Pyramiding-Senkron: {0} epic doğru'),
    ('Session yok (oturum kapali)',
     'Keine Session (Sitzung geschlossen)',
     'No session (session closed)',
     'Session yok (oturum kapalı)'),
    ('MA hesaplanamadı',
     'MA konnte nicht berechnet werden',
     'MA could not be calculated',
     'MA hesaplanamadı'),
    ('TF uyumsuz | {0}',
     'TF nicht im Einklang | {0}',
     'TF not aligned | {0}',
     'TF uyumsuz | {0}'),
    ('20m:{0}({1}/3) 45m:{2}({3}/3) 2h:{4}({5}/3) → {6}/3 TF uyumlu',
     '20m:{0}({1}/3) 45m:{2}({3}/3) 2h:{4}({5}/3) → {6}/3 TF im Einklang',
     '20m:{0}({1}/3) 45m:{2}({3}/3) 2h:{4}({5}/3) → {6}/3 TF aligned',
     '20m:{0}({1}/3) 45m:{2}({3}/3) 2h:{4}({5}/3) → {6}/3 TF uyumlu'),
    ('Sinyal zayıf | {0}',
     'Signal schwach | {0}',
     'Signal weak | {0}',
     'Sinyal zayıf | {0}'),
    ('Key yok',
     'Kein Key',
     'No key',
     'Key yok'),
    ('Modeller basarisiz',
     'Modelle fehlgeschlagen',
     'Models failed',
     'Modeller başarısız'),
    ('KARA KUĞU ACİL!\n>%{0} kayıp!\nTÜM POZİSYONLAR KAPATILIYOR!',
     'SCHWARZER SCHWAN NOTFALL!\n>{0} % Verlust!\nALLE POSITIONEN WERDEN GESCHLOSSEN!',
     'BLACK SWAN EMERGENCY!\n>{0}% loss!\nALL POSITIONS ARE BEING CLOSED!',
     'KARA KUĞU ACİL!\n>%{0} kayıp!\nTÜM POZİSYONLAR KAPATILIYOR!'),
    ('NOTFALL-KAPAT {0}: {1}EUR',
     'NOTFALL-SCHLIESSUNG {0}: {1}EUR',
     'EMERGENCY CLOSE {0}: {1}EUR',
     'ACİL KAPATMA {0}: {1}EUR'),
    ('ACİL KAPATMA TAMAMLANDI:\n',
     'NOTFALL-SCHLIESSUNG ABGESCHLOSSEN:\n',
     'EMERGENCY CLOSE COMPLETED:\n',
     'ACİL KAPATMA TAMAMLANDI:\n'),
    ('TUT hakki bitti',
     'HALTEN bereits verbraucht',
     'HOLD already used up',
     'TUT hakkı bitti'),
    ('KARA KUGU ({0}%)\nAsset: {1} | UPL:{2}EUR\nGemini: {3} - {4}',
     'SCHWARZER SCHWAN ({0}%)\nAsset: {1} | UPL:{2}EUR\nGemini: {3} - {4}',
     'BLACK SWAN ({0}%)\nAsset: {1} | UPL:{2}EUR\nGemini: {3} - {4}',
     'KARA KUĞU (%{0})\nAsset: {1} | UPL:{2}EUR\nGemini: {3} - {4}'),
    ('KARA_KUGU(Gemini→KAPAT) {0}: {1}%',
     'KARA_KUGU(Gemini→SCHLIESSEN) {0}: {1}%',
     'KARA_KUGU(Gemini→CLOSE) {0}: {1}%',
     'KARA_KUGU(Gemini→KAPAT) {0}: %{1}'),
    ('KARA_KUGU(Hedge→KAPAT) {0}: hedge basarisiz',
     'KARA_KUGU(Hedge→SCHLIESSEN) {0}: Hedge fehlgeschlagen',
     'KARA_KUGU(Hedge→CLOSE) {0}: hedge failed',
     'KARA_KUGU(Hedge→KAPAT) {0}: hedge başarısız'),
    ('KARA_KUGU(Gemini→TUT) {0}: 1x TUT kullanildi',
     'KARA_KUGU(Gemini→HALTEN) {0}: 1x HALTEN verbraucht',
     'KARA_KUGU(Gemini→HOLD) {0}: 1x HOLD used',
     'KARA_KUGU(Gemini→TUT) {0}: 1x TUT kullanıldı'),
    ('KARA_KUGU(AUTO) {0}: {1}% | {2}EUR',
     'KARA_KUGU(AUTO) {0}: {1}% | {2}EUR',
     'KARA_KUGU(AUTO) {0}: {1}% | {2}EUR',
     'KARA_KUGU(AUTO) {0}: %{1} | {2}EUR'),
    ('KARA KUĞU ALARMI!\n',
     'SCHWARZER-SCHWAN-ALARM!\n',
     'BLACK SWAN ALERT!\n',
     'KARA KUĞU ALARMI!\n'),
    ('Ilk giris',
     'Erster Einstieg',
     'First entry',
     'İlk giriş'),
    ('Pozisyon %{0} karda - Pyramiding izinli',
     'Position {0} % im Gewinn - Pyramiding erlaubt',
     'Position {0}% in profit - Pyramiding allowed',
     'Pozisyon %{0} kârda - Pyramiding izinli'),
    ('Pozisyon sadece %{0} karda - Min %2 gerekli',
     'Position nur {0} % im Gewinn - mindestens 2 % nötig',
     'Position only {0}% in profit - at least 2% required',
     'Pozisyon sadece %{0} kârda - en az %2 gerekli'),
    ('Pyramiding icin yeterli kar yok',
     'Nicht genug Gewinn für Pyramiding',
     'Not enough profit for Pyramiding',
     'Pyramiding için yeterli kâr yok'),
    ('Konto-Einstellungen nicht lesbar (HTTP {0})',
     'Konto-Einstellungen nicht lesbar (HTTP {0})',
     'Account settings not readable (HTTP {0})',
     'Hesap ayarları okunamadı (HTTP {0})'),
    ('keine offene Position gefunden',
     'keine offene Position gefunden',
     'no open position found',
     'açık pozisyon bulunamadı'),
    ('Order abgelehnt: {0}',
     'Order abgelehnt: {0}',
     'Order rejected: {0}',
     'Emir reddedildi: {0}'),
    ('Breakeven: {0} {1} +{2}% → SL={3}',
     'Breakeven: {0} {1} +{2}% → SL={3}',
     'Breakeven: {0} {1} +{2}% → SL={3}',
     'Breakeven: {0} {1} +%{2} → SL={3}'),
    ('Schliessen abgelehnt: {0}',
     'Schliessen abgelehnt: {0}',
     'Close rejected: {0}',
     'Kapatma reddedildi: {0}'),
    ('Position damit komplett geschlossen.',
     'Position damit komplett geschlossen.',
     'Position is now fully closed.',
     'Pozisyon böylece tamamen kapatıldı.'),
    ('Rest {0} läuft weiter.',
     'Rest {0} läuft weiter.',
     'Remaining {0} keeps running.',
     'Kalan {0} açık kalıyor.'),
    ('🎯 MIRROR-TP Level {0}: {1} {2}\n✅ {3} von {4} Einheiten geschlossen ({5}%) @ {6}\n📊 ATR-Ziel: {7} | {8}',
     '🎯 MIRROR-TP Level {0}: {1} {2}\n✅ {3} von {4} Einheiten geschlossen ({5}%) @ {6}\n📊 ATR-Ziel: {7} | {8}',
     '🎯 MIRROR-TP Level {0}: {1} {2}\n✅ {3} of {4} units closed ({5}%) @ {6}\n📊 ATR target: {7} | {8}',
     '🎯 MIRROR-TP Kademe {0}: {1} {2}\n✅ {4} birimden {3} birim kapatıldı (%{5}) @ {6}\n📊 ATR hedefi: {7} | {8}'),
    ('Teilverkauf nicht möglich: Im Capital.com-Konto ist der Hedging-Modus eingeschaltet. Bitte dort ausschalten, dann verkauft der Bot in Stufen.',
     'Teilverkauf nicht möglich: Im Capital.com-Konto ist der Hedging-Modus eingeschaltet. Bitte dort ausschalten, dann verkauft der Bot in Stufen.',
     'Partial sale not possible: Hedging mode is switched on in the Capital.com account. Please switch it off there, then the bot will sell in levels.',
     'Kısmi satış mümkün değil: Capital.com hesabında Hedging modu açık. Lütfen orada kapat, sonra bot kademeli olarak satar.'),
    ('Order gesendet, aber im Depot keine Verkleinerung gesehen. Stufe wird NICHT wiederholt - bitte Position prüfen.',
     'Order gesendet, aber im Depot keine Verkleinerung gesehen. Stufe wird NICHT wiederholt - bitte Position prüfen.',
     'Order sent, but no reduction seen in the account. Level will NOT be repeated - please check the position.',
     'Emir gönderildi, ancak hesapta küçülme görülmedi. Kademe TEKRARLANMAYACAK - lütfen pozisyonu kontrol et.'),
    ('Statt eines Teilverkaufs entstand eine Gegenposition; sie wurde sofort wieder geschlossen. Bitte Depot prüfen.',
     'Statt eines Teilverkaufs entstand eine Gegenposition; sie wurde sofort wieder geschlossen. Bitte Depot prüfen.',
     'Instead of a partial sale, an opposite position was created; it was closed again immediately. Please check the account.',
     'Kısmi satış yerine ters pozisyon oluştu; hemen tekrar kapatıldı. Lütfen hesabı kontrol et.'),
    ('{0} - wird beim nächsten Durchlauf erneut versucht.',
     '{0} - wird beim nächsten Durchlauf erneut versucht.',
     '{0} - will be retried in the next cycle.',
     '{0} - sonraki döngüde tekrar denenecek.'),
    ('⚠️ MIRROR-TP Level {0}: {1} {2}\n{3}',
     '⚠️ MIRROR-TP Level {0}: {1} {2}\n{3}',
     '⚠️ MIRROR-TP Level {0}: {1} {2}\n{3}',
     '⚠️ MIRROR-TP Kademe {0}: {1} {2}\n{3}'),
    ('Partial Exit: {0} {1} +{2}% | {3} units gesichert',
     'Teilausstieg: {0} {1} +{2}% | {3} Einheiten gesichert',
     'Partial exit: {0} {1} +{2}% | {3} units secured',
     'Kısmi çıkış: {0} {1} +%{2} | {3} birim güvenceye alındı'),
    ('SL Guncellendi: ',
     'SL aktualisiert: ',
     'SL updated: ',
     'SL Güncellendi: '),
    (' | Yeni SL: ',
     ' | Neuer SL: ',
     ' | New SL: ',
     ' | Yeni SL: '),
    ('Haber DB henuz hazir degil - /newscollect ile doldurun',
     'Nachrichten-DB noch nicht bereit - mit /news_sammeln füllen',
     'News DB not ready yet - fill it with /newscollect',
     'Haber DB henüz hazır değil - /haber_topla ile doldur'),
    ('Son 3 gun icin genel haber yok.',
     'Keine allgemeinen Nachrichten für die letzten 3 Tage.',
     'No general news for the last 3 days.',
     'Son 3 gün için genel haber yok.'),
    ('=== {0} | GENEL MAKRO HABERLER (Son {1} Gun) ===',
     '=== {0} | ALLGEMEINE MAKRO-NACHRICHTEN (letzte {1} Tage) ===',
     '=== {0} | GENERAL MACRO NEWS (last {1} days) ===',
     '=== {0} | GENEL MAKRO HABERLER (Son {1} Gün) ==='),
    ('\nONE CIKAN X POSTLARI:',
     '\nWICHTIGSTE X-POSTS:',
     '\nTOP X POSTS:',
     '\nÖNE ÇIKAN X POSTLARI:'),
    ('Haber Toplayici: RSS={0} | GDELT={1} | AlphaVantage={2} haber | Kaynaklar: {3} X + {4} site',
     'Nachrichtensammler: RSS={0} | GDELT={1} | AlphaVantage={2} Nachrichten | Quellen: {3} X + {4} Seiten',
     'News collector: RSS={0} | GDELT={1} | AlphaVantage={2} news | Sources: {3} X + {4} sites',
     'Haber Toplayıcı: RSS={0} | GDELT={1} | AlphaVantage={2} haber | Kaynaklar: {3} X + {4} site'),
    ('Sinyal yok/zayıf (guc={0})',
     'Kein/schwaches Signal (Stärke={0})',
     'No/weak signal (strength={0})',
     'Sinyal yok/zayıf (güç={0})'),
    ('RISK_OFF_EXTREME — sadece altın/gümüş',
     'RISK_OFF_EXTREME — nur Gold/Silber',
     'RISK_OFF_EXTREME — gold/silver only',
     'RISK_OFF_EXTREME — sadece altın/gümüş'),
    ('Gece kriptoda makro belirsizlik',
     'Nachts Makro-Unsicherheit bei Krypto',
     'Macro uncertainty in crypto at night',
     'Gece kriptoda makro belirsizlik'),
    ('Makro uygun ({0})',
     'Makro passt ({0})',
     'Macro favorable ({0})',
     'Makro uygun ({0})'),
    ('Krypto haftasonu — katalyzör yok',
     'Krypto am Wochenende — kein Katalysator',
     'Crypto on the weekend — no catalyst',
     'Kripto hafta sonu — katalizör yok'),
    ('Rogers-Filter aktif — EMA200 onayı',
     'Rogers-Filter aktiv — EMA200-Bestätigung',
     'Rogers filter active — EMA200 confirmation',
     'Rogers filtresi aktif — EMA200 onayı'),
    ('Emtia sinyali güçlü (guc={0})',
     'Rohstoff-Signal stark (Stärke={0})',
     'Commodity signal strong (strength={0})',
     'Emtia sinyali güçlü (güç={0})'),
    ('Güçlü sinyal (guc=3)',
     'Starkes Signal (Stärke=3)',
     'Strong signal (strength=3)',
     'Güçlü sinyal (güç=3)'),
    ('Yeterli fundamental katalysator yok',
     'Kein ausreichender fundamentaler Katalysator',
     'No sufficient fundamental catalyst',
     'Yeterli temel katalizör yok'),
    ('UPL çok negatif ({0}€)',
     'UPL stark negativ ({0}€)',
     'UPL very negative ({0}€)',
     'UPL çok negatif ({0}€)'),
    ('FRED olumsuz ({0})',
     'FRED ungünstig ({0})',
     'FRED unfavorable ({0})',
     'FRED olumsuz ({0})'),
    ('Haftasonu — likidite riski',
     'Wochenende — Liquiditätsrisiko',
     'Weekend — liquidity risk',
     'Hafta sonu — likidite riski'),
    ('Sinyal zayıf',
     'Signal schwach',
     'Signal weak',
     'Sinyal zayıf'),
    ('Risk dengesi uygun (UPL={0}€)',
     'Risikobalance passt (UPL={0}€)',
     'Risk balance favorable (UPL={0}€)',
     'Risk dengesi uygun (UPL={0}€)'),
    ('Kuyruk riski ({0})',
     'Tail-Risiko ({0})',
     'Tail risk ({0})',
     'Kuyruk riski ({0})'),
    ('Gece+Haftasonu+Krypto=max belirsizlik',
     'Nacht+Wochenende+Krypto=max. Unsicherheit',
     'Night+weekend+crypto=max uncertainty',
     'Gece+Hafta sonu+Kripto=maks. belirsizlik'),
    ('Haber sentiment çok negatif ({0})',
     'Nachrichten-Sentiment stark negativ ({0})',
     'News sentiment very negative ({0})',
     'Haber sentiment çok negatif ({0})'),
    ('Kuyruk riski kabul edilebilir',
     'Tail-Risiko akzeptabel',
     'Tail risk acceptable',
     'Kuyruk riski kabul edilebilir'),
    ('Belirsizlik fazla',
     'Zu viel Unsicherheit',
     'Too much uncertainty',
     'Belirsizlik fazla'),
    ('Yön yok — reflexivite işlemez',
     'Keine Richtung — Reflexivität greift nicht',
     'No direction — reflexivity does not work',
     'Yön yok — refleksivite işlemez'),
    ('Gece — likidite düşük',
     'Nacht — geringe Liquidität',
     'Night — low liquidity',
     'Gece — likidite düşük'),
    ('Momentum güçlü (guc={0})',
     'Momentum stark (Stärke={0})',
     'Momentum strong (strength={0})',
     'Momentum güçlü (güç={0})'),
    ('Çok güçlü sinyal',
     'Sehr starkes Signal',
     'Very strong signal',
     'Çok güçlü sinyal'),
    ('Momentum yetersiz (guc={0})',
     'Momentum zu schwach (Stärke={0})',
     'Momentum insufficient (strength={0})',
     'Momentum yetersiz (güç={0})'),
    ('API Baglanti Hatasi',
     'API-Verbindungsfehler',
     'API connection error',
     'API Bağlantı Hatası'),
    ('❌ API bağlantı hatası',
     '❌ API-Verbindungsfehler',
     '❌ API connection error',
     '❌ API bağlantı hatası'),
    (' - Yeni trade ACILMIYOR',
     ' - neuer Trade wird NICHT ERÖFFNET',
     ' - new trade NOT OPENED',
     ' - Yeni trade AÇILMIYOR'),
    ('DEPOT DD ALARMI: ',
     'DEPOT-DD-ALARM: ',
     'ACCOUNT DD ALERT: ',
     'HESAP DD ALARMI: '),
    ('⛔ MAX POSITIONEN: {0}/{1} erreicht - keine neuen Trades',
     '⛔ MAX POSITIONEN: {0}/{1} erreicht - keine neuen Trades',
     '⛔ MAX POSITIONS: {0}/{1} reached - no new trades',
     '⛔ MAKS POZİSYON: {0}/{1} sınırına ulaşıldı - yeni trade yok'),
    ("{0} config'de bulunamadi (esleme basarisiz)",
     '{0} nicht in der Config gefunden (Zuordnung fehlgeschlagen)',
     '{0} not found in config (mapping failed)',
     "{0} config'de bulunamadı (eşleme başarısız)"),
    ('⛔ FALLBACK-BLOCK {0} ({1}): nicht vom Gate-Keeper freigegeben (erlaubt: {2})',
     '⛔ FALLBACK-BLOCK {0} ({1}): nicht vom Gate-Keeper freigegeben (erlaubt: {2})',
     '⛔ FALLBACK-BLOCK {0} ({1}): not approved by the Gate-Keeper (allowed: {2})',
     '⛔ FALLBACK-BLOCK {0} ({1}): Gate-Keeper onaylamadı (izinli: {2})'),
    ('TABU {0}: Kesinlikle trade yapilmaz',
     'TABU {0}: Wird auf keinen Fall gehandelt',
     'TABOO {0}: No trading under any circumstances',
     'TABU {0}: Kesinlikle trade yapılmaz'),
    ('⛔ HARD BLOCK {0} ({1}): Kullanici talimati aktif — {2}',
     '⛔ HARD BLOCK (Handelssperre) {0} ({1}): Benutzeranweisung aktiv — {2}',
     '⛔ HARD BLOCK {0} ({1}): user instruction active — {2}',
     '⛔ HARD BLOCK {0} ({1}): Kullanıcı talimatı aktif — {2}'),
    ('Kripto 7/24 açık olmalı — Capital.com oturumu kontrol et',
     'Krypto sollte 24/7 offen sein — Capital.com-Sitzung prüfen',
     'Crypto should be open 24/7 — check the Capital.com session',
     'Kripto 7/24 açık olmalı — Capital.com oturumu kontrol et'),
    ('Pazartesi 00:00 UTC (Forex) / 02:00 UTC (Emtia)',
     'Montag 00:00 UTC (Forex) / 02:00 UTC (Rohstoffe)',
     'Monday 00:00 UTC (Forex) / 02:00 UTC (commodities)',
     'Pazartesi 00:00 UTC (Forex) / 02:00 UTC (Emtia)'),
    ('Yarın 00:00 UTC (Forex) / 02:00 UTC (Emtia)',
     'Morgen 00:00 UTC (Forex) / 02:00 UTC (Rohstoffe)',
     'Tomorrow 00:00 UTC (Forex) / 02:00 UTC (commodities)',
     'Yarın 00:00 UTC (Forex) / 02:00 UTC (Emtia)'),
    ('Bugün açılacak — şu an {0}:xx UTC, bekleniyor',
     'Öffnet heute — aktuell {0}:xx UTC, es wird gewartet',
     'Opens today — currently {0}:xx UTC, waiting',
     'Bugün açılacak — şu an {0}:xx UTC, bekleniyor'),
    ('Durum: {0} — Capital.com panelini kontrol et',
     'Status: {0} — Capital.com-Oberfläche prüfen',
     'Status: {0} — check the Capital.com dashboard',
     'Durum: {0} — Capital.com panelini kontrol et'),
    ('⏰ PİYASA KAPALI: {0}\nDurum: {1}\nTahmini açılış: {2}\n→ Trade planlandı ama şu an işlem yapılamaz',
     '⏰ MARKT GESCHLOSSEN: {0}\nStatus: {1}\nVoraussichtliche Öffnung: {2}\n→ Trade geplant, aber gerade ist kein Handel möglich',
     '⏰ MARKET CLOSED: {0}\nStatus: {1}\nEstimated opening: {2}\n→ Trade planned, but trading is not possible right now',
     '⏰ PİYASA KAPALI: {0}\nDurum: {1}\nTahmini açılış: {2}\n→ Trade planlandı ama şu an işlem yapılamaz'),
    ('⛔ SPREAD BLOK {0}: Canli spread {1} > MAX_SPREAD {2} (.env) - Gemini onerse dahi ISLEM REDDEDILDI',
     '⛔ SPREAD-BLOCK {0}: Live-Spread {1} > MAX_SPREAD {2} (.env) - TRADE ABGELEHNT, auch wenn Gemini ihn empfiehlt',
     '⛔ SPREAD BLOCK {0}: live spread {1} > MAX_SPREAD {2} (.env) - TRADE REJECTED even if Gemini recommends it',
     '⛔ SPREAD BLOK {0}: Canlı spread {1} > MAX_SPREAD {2} (.env) - Gemini önerse dahi İŞLEM REDDEDİLDİ'),
    ('⚠️ UYARI {0}: Bugun {1}x kayip var - Gremium dikkatli olsun',
     '⚠️ WARNUNG {0}: Heute {1}x Verlust - Gremium soll vorsichtig sein',
     '⚠️ WARNING {0}: {1}x loss today - committee should be careful',
     '⚠️ UYARI {0}: Bugün {1}x kayıp var - Kurul dikkatli olsun'),
    ('🔴 HARD BLOK {0}: Bugun {1}x kayip (limit={2}) - trade durduruldu',
     '🔴 HARD BLOCK (Handelssperre) {0}: Heute {1}x Verlust (Limit={2}) - Trade gestoppt',
     '🔴 HARD BLOCK {0}: {1}x loss today (limit={2}) - trade stopped',
     '🔴 HARD BLOCK {0}: Bugün {1}x kayıp (limit={2}) - trade durduruldu'),
    ('{0}: {1}/{2} kapatıldı (ÇIKIŞ)',
     '{0}: {1}/{2} geschlossen (AUSSTIEG)',
     '{0}: {1}/{2} closed (EXIT)',
     '{0}: {1}/{2} kapatıldı (ÇIKIŞ)'),
    ('⛔ {0}: Gegenposition NICHT eroeffnet - Groesse ausserhalb der .env-Limits',
     '⛔ {0}: Gegenposition NICHT eroeffnet - Groesse ausserhalb der .env-Limits',
     '⛔ {0}: counter-position NOT opened - size outside the .env limits',
     '⛔ {0}: Karşı pozisyon AÇILMADI - büyüklük .env limitlerinin dışında'),
    ('{0} SL güncellendi: {1} -> {2} ({3})',
     '{0} SL aktualisiert: {1} -> {2} ({3})',
     '{0} SL updated: {1} -> {2} ({3})',
     '{0} SL güncellendi: {1} -> {2} ({3})'),
    ('{0} karşı pozisyon açıldı ({1}) Stufe 1/4',
     '{0} Gegenposition eröffnet ({1}) Stufe 1/4',
     '{0} counter-position opened ({1}) Level 1/4',
     '{0} karşı pozisyon açıldı ({1}) Seviye 1/4'),
    ('{0} karşı pozisyon BAŞARISIZ: {1}',
     '{0} Gegenposition FEHLGESCHLAGEN: {1}',
     '{0} counter-position FAILED: {1}',
     '{0} karşı pozisyon BAŞARISIZ: {1}'),
    ('{0} engellendi: Haftasonu - sadece kripto!',
     '{0} blockiert: Wochenende - nur Krypto!',
     '{0} blocked: weekend - crypto only!',
     '{0} engellendi: Hafta sonu - sadece kripto!'),
    ('{0} engellendi: Haftasonu kripto limiti 3/3',
     '{0} blockiert: Wochenend-Krypto-Limit 3/3',
     '{0} blocked: weekend crypto limit 3/3',
     '{0} engellendi: Hafta sonu kripto limiti 3/3'),
    ('⏳ {0} {1}: vor {2} min geschlossen - Wiedereinstieg gesperrt, noch {3} h {4} min (WIEDEREINSTIEG_SPERRE_STD={5})',
     '⏳ {0} {1}: vor {2} min geschlossen - Wiedereinstieg gesperrt, noch {3} h {4} min (WIEDEREINSTIEG_SPERRE_STD={5})',
     '⏳ {0} {1}: closed {2} min ago - re-entry locked for another {3} h {4} min (WIEDEREINSTIEG_SPERRE_STD={5})',
     '⏳ {0} {1}: {2} dk önce kapatıldı - yeniden giriş kilitli, kalan süre {3} sa {4} dk (WIEDEREINSTIEG_SPERRE_STD={5})'),
    ('⛔ {0}: MAX POSITIONEN {1}/{2} erreicht - nicht eröffnet',
     '⛔ {0}: MAX POSITIONEN {1}/{2} erreicht - nicht eröffnet',
     '⛔ {0}: MAX POSITIONS {1}/{2} reached - not opened',
     '⛔ {0}: MAKS POZİSYON {1}/{2} sınırına ulaşıldı - açılmadı'),
    ('{0} Pyramiding atlandı: {1}',
     '{0} Pyramiding übersprungen: {1}',
     '{0} Pyramiding skipped: {1}',
     '{0} Pyramiding atlandı: {1}'),
    ('⚠️ {0} backtest zayif (WR<35% veya yetersiz veri) - trade devam ediyor ama dikkat!',
     '⚠️ {0} Backtest schwach (WR<35% oder zu wenige Daten) - Trade läuft weiter, aber Vorsicht!',
     '⚠️ {0} backtest weak (WR<35% or not enough data) - trade continues, but be careful!',
     '⚠️ {0} backtest zayıf (WR<%35 veya yetersiz veri) - trade devam ediyor ama dikkat!'),
    ('⛔ {0}: kein Live-Preis von Capital.com -> Trade verworfen',
     '⛔ {0}: kein Live-Preis von Capital.com -> Trade verworfen',
     '⛔ {0}: no live price from Capital.com -> trade discarded',
     "⛔ {0}: Capital.com'dan canlı fiyat yok -> trade iptal edildi"),
    ('⛔ {0} {1}: SL/TP unplausibel (Kurs {2}, SL {3}, TP {4}) -> Trade verworfen',
     '⛔ {0} {1}: SL/TP unplausibel (Kurs {2}, SL {3}, TP {4}) -> Trade verworfen',
     '⛔ {0} {1}: SL/TP implausible (price {2}, SL {3}, TP {4}) -> trade discarded',
     '⛔ {0} {1}: SL/TP makul değil (fiyat {2}, SL {3}, TP {4}) -> trade iptal edildi'),
    ('⛔ {0}: Groesse ausserhalb der .env-Limits oder Depot/Kurs nicht lesbar -> kein Trade',
     '⛔ {0}: Groesse ausserhalb der .env-Limits oder Depot/Kurs nicht lesbar -> kein Trade',
     '⛔ {0}: size outside the .env limits or account/price not readable -> no trade',
     '⛔ {0}: büyüklük .env limitlerinin dışında veya hesap/fiyat okunamadı -> trade yok'),
    ('Margin ENGEL: {0}',
     'Margin-SPERRE: {0}',
     'Margin BLOCK: {0}',
     'Margin ENGEL: {0}'),
    ('✅ POZİSYON ONAYLANDI: {0}\nYön: {1} | Size: {2}\nSL: {3} | TP: {4}\nCapital.com depo doğrulandı ✓',
     '✅ POSITION BESTÄTIGT: {0}\nRichtung: {1} | Größe: {2}\nSL: {3} | TP: {4}\nCapital.com-Depot verifiziert ✓',
     '✅ POSITION CONFIRMED: {0}\nDirection: {1} | Size: {2}\nSL: {3} | TP: {4}\nCapital.com account verified ✓',
     '✅ POZİSYON ONAYLANDI: {0}\nYön: {1} | Büyüklük: {2}\nSL: {3} | TP: {4}\nCapital.com hesabı doğrulandı ✓'),
    ('⚠️ POZİSYON DOĞRULANAMADI: {0}\nOrder gönderildi (HTTP 200) ama depoda pozisyon görünmüyor.\nOlası neden: Piyasa kapalı veya Capital.com gecikmesi.\n→ Lütfen Capital.com panelini kontrol et!',
     '⚠️ POSITION NICHT BESTÄTIGT: {0}\nOrder gesendet (HTTP 200), aber im Depot ist keine Position sichtbar.\nMögliche Ursache: Markt geschlossen oder Verzögerung bei Capital.com.\n→ Bitte prüfe das Capital.com-Panel!',
     '⚠️ POSITION NOT VERIFIED: {0}\nOrder sent (HTTP 200) but no position is visible in the account.\nPossible cause: market closed or Capital.com delay.\n→ Please check the Capital.com panel!',
     '⚠️ POZİSYON DOĞRULANAMADI: {0}\nOrder gönderildi (HTTP 200) ama hesapta pozisyon görünmüyor.\nOlası neden: Piyasa kapalı veya Capital.com gecikmesi.\n→ Lütfen Capital.com panelini kontrol et!'),
    ('{0} yeni pozisyon açıldı ({1}) Seviye {2}',
     '{0} neue Position eröffnet ({1}) Stufe {2}',
     '{0} new position opened ({1}) Level {2}',
     '{0} yeni pozisyon açıldı ({1}) Seviye {2}'),
    ('{0} SL/TP senkron: {1} Pos -> SL:{2} TP:{3}',
     '{0} SL/TP synchronisiert: {1} Pos -> SL:{2} TP:{3}',
     '{0} SL/TP synced: {1} pos -> SL:{2} TP:{3}',
     '{0} SL/TP senkron: {1} Pos -> SL:{2} TP:{3}'),
    ('{0} Trailing SL aktif: -%5 ({1} peak = Einstandspreis)',
     '{0} Trailing SL aktiv: -5 % ({1} Peak = Einstandspreis)',
     '{0} Trailing SL active: -5% ({1} peak = entry price)',
     '{0} Trailing SL aktif: -%5 ({1} peak = giriş fiyatı)'),
    ('{0} açılış hatası: {1}',
     '{0} Fehler beim Eröffnen: {1}',
     '{0} opening error: {1}',
     '{0} açılış hatası: {1}'),
    ('Piramiding Senkron: {0}',
     'Pyramiding synchron: {0}',
     'Pyramiding sync: {0}',
     'Pyramiding Senkron: {0}'),
    ('🔍 {0} | NEXUS NATURE v12.0 - Analiz yapılıyor...',
     '🔍 {0} | NEXUS NATURE v12.0 - Analyse läuft...',
     '🔍 {0} | NEXUS NATURE v12.0 - Analysis running...',
     '🔍 {0} | NEXUS NATURE v12.0 - Analiz yapılıyor...'),
    ('   Größe {0} | Einstieg {1} | Kurs {2}',
     '   Größe {0} | Einstieg {1} | Kurs {2}',
     '   Size {0} | Entry {1} | Price {2}',
     '   Büyüklük {0} | Giriş {1} | Fiyat {2}'),
    ('   🛑 SL {0} ({1}% vom Einstieg)',
     '   🛑 SL {0} ({1}% vom Einstieg)',
     '   🛑 SL {0} ({1}% from entry)',
     '   🛑 SL {0} (girişe göre %{1})'),
    ('   🛑 SL: KEINER gesetzt',
     '   🛑 SL: KEINER gesetzt',
     '   🛑 SL: NONE set',
     '   🛑 SL: AYARLANMAMIŞ'),
    ('   🎯 TP {0} (noch {1}%)',
     '   🎯 TP {0} (noch {1}%)',
     '   🎯 TP {0} ({1}% to go)',
     '   🎯 TP {0} (kalan %{1})'),
    ('   🎯 TP: KEINER gesetzt',
     '   🎯 TP: KEINER gesetzt',
     '   🎯 TP: NONE set',
     '   🎯 TP: AYARLANMAMIŞ'),
    ('   📏 Ø Tagesspanne (ATR {0} T): {1} = {2}%',
     '   📏 Ø Tagesspanne (ATR {0} T): {1} = {2}%',
     '   📏 Ø daily range (ATR {0} d): {1} = {2}%',
     '   📏 Ø günlük aralık (ATR {0} gün): {1} = %{2}'),
    ('   Tagesziel {0}% davon: {1} ',
     '   Tagesziel {0}% davon: {1} ',
     '   Daily target {0}% of that: {1} ',
     '   Günlük hedef, bunun %{0} kadarı: {1} '),
    ('✅ erreicht - der Bot fragt dich',
     '✅ erreicht - der Bot fragt dich',
     '✅ reached - the bot will ask you',
     '✅ ulaşıldı - bot sana soracak'),
    ('(noch {0}%) → dann fragt der Bot',
     '(noch {0}%) → dann fragt der Bot',
     '({0}% to go) → then the bot will ask',
     '(kalan %{0}) → sonra bot soracak'),
    ('   Stop-Abstand = {0} × Tagesspanne',
     '   Stop-Abstand = {0} × Tagesspanne',
     '   Stop distance = {0} × daily range',
     '   Stop mesafesi = {0} × günlük aralık'),
    (' ⚠️ im Tagesrauschen → /sl_weiten',
     ' ⚠️ im Tagesrauschen → /sl_weiten',
     ' ⚠️ within daily noise → /sl_widen',
     ' ⚠️ günlük gürültü içinde → /sl_genislet'),
    ('   📏 Ø Tagesspanne: gerade nicht abrufbar',
     '   📏 Ø Tagesspanne: gerade nicht abrufbar',
     '   📏 Ø daily range: currently unavailable',
     '   📏 Ø günlük aralık: şu an alınamıyor'),
    ('L{0} {1} ✅ verkauft',
     'L{0} {1} ✅ verkauft',
     'L{0} {1} ✅ sold',
     'L{0} {1} ✅ satıldı'),
    ('L{0} {1} ⏳ erreicht',
     'L{0} {1} ⏳ erreicht',
     'L{0} {1} ⏳ reached',
     'L{0} {1} ⏳ ulaşıldı'),
    ('L{0} {1} (noch {2}%)',
     'L{0} {1} (noch {2}%)',
     'L{0} {1} ({2}% to go)',
     'L{0} {1} (kalan %{2})'),
    ('   🪜 Mirror-TP Stufen (Stunden-ATR {0}):',
     '   🪜 Mirror-TP Stufen (Stunden-ATR {0}):',
     '   🪜 Mirror-TP levels (hourly ATR {0}):',
     '   🪜 Mirror-TP kademeleri (saatlik ATR {0}):'),
    ('   🪜 Mirror-TP: Stunden-ATR gerade nicht abrufbar',
     '   🪜 Mirror-TP: Stunden-ATR gerade nicht abrufbar',
     '   🪜 Mirror-TP: hourly ATR currently unavailable',
     '   🪜 Mirror-TP: saatlik ATR şu an alınamıyor'),
    ('   🪜 Mirror-TP: aus (.env)',
     '   🪜 Mirror-TP: aus (.env)',
     '   🪜 Mirror-TP: off (.env)',
     '   🪜 Mirror-TP: kapalı (.env)'),
    ('   Breakeven-SL ab +1.0% | Trailing-SL ab +1.5% (5% unter dem Hoch)',
     '   Breakeven-SL ab +1.0% | Trailing-SL ab +1.5% (5% unter dem Hoch)',
     '   Breakeven-SL from +1.0% | Trailing-SL from +1.5% (5% below the high)',
     "   Breakeven-SL +%1.0'dan itibaren | Trailing-SL +%1.5'ten itibaren (zirvenin %5 altında)"),
    ('Açık pozisyon yok.',
     'Keine offenen Positionen.',
     'No open positions.',
     'Açık pozisyon yok.'),
    ('– VORSCHAU (nichts geändert)',
     '– VORSCHAU (nichts geändert)',
     '– PREVIEW (nothing changed)',
     '– ÖNİZLEME (hiçbir şey değişmedi)'),
    ('– AUSGEFÜHRT',
     '– AUSGEFÜHRT',
     '– EXECUTED',
     '– UYGULANDI'),
    ('🛑 STOPS AUF TAGESSPANNE ',
     '🛑 STOPS AUF TAGESSPANNE ',
     '🛑 STOPS TO DAILY RANGE ',
     '🛑 STOPLAR GÜNLÜK ARALIĞA '),
    ('\n{0} Stop(s) würden geweitet. Ausführen mit:  /sl_weiten ja',
     '\n{0} Stop(s) würden geweitet. Ausführen mit:  /sl_weiten ja',
     '\n{0} stop(s) would be widened. Execute with:  /sl_widen yes',
     '\n{0} stop genişletilecek. Uygulamak için:  /sl_genislet evet'),
    ('\nNichts zu tun - kein Stop liegt im Tagesrauschen.',
     '\nNichts zu tun - kein Stop liegt im Tagesrauschen.',
     '\nNothing to do - no stop is within daily noise.',
     '\nYapılacak bir şey yok - hiçbir stop günlük gürültü içinde değil.'),
    ('❌ /sl_weiten: {0}',
     '❌ /sl_weiten: {0}',
     '❌ /sl_widen: {0}',
     '❌ /sl_genislet: {0}'),
    ('❌ Modell-Update: {0}',
     '❌ Modell-Update: {0}',
     '❌ Model update: {0}',
     '❌ Model güncellemesi: {0}'),
    ('❌ API bağlantısı kurulamadı',
     '❌ API-Verbindung konnte nicht hergestellt werden',
     '❌ Could not establish API connection',
     '❌ API bağlantısı kurulamadı'),
    ('📊 {0} | NEXUS POZİSYON RAPORU\n',
     '📊 {0} | NEXUS POSITIONSBERICHT\n',
     '📊 {0} | NEXUS POSITION REPORT\n',
     '📊 {0} | NEXUS POZİSYON RAPORU\n'),
    ('Nakit: {0} EUR\n',
     'Kontostand: {0} EUR\n',
     'Balance: {0} EUR\n',
     'Nakit: {0} EUR\n'),
    ('• {0}: {1} UPL:{2} ({3}%) Pyr:Sv.{4}\n',
     '• {0}: {1} UPL:{2} ({3}%) Pyr:St.{4}\n',
     '• {0}: {1} UPL:{2} ({3}%) Pyr:Lv.{4}\n',
     '• {0}: {1} UPL:{2} (%{3}) Pyr:Sv.{4}\n'),
    ('Kullanim: /kapat SYMBOL  veya  /kapat ALLE\nOrnekler:\n  /kapat GOLD\n  /kapat NATURAL_GAS\n  /kapat ALLE          (once onay ister)\n  /kapat ALLE ONAYLA   (gercekten hepsini kapatir)',
     'Verwendung: /schliessen SYMBOL  oder  /schliessen ALLE\nBeispiele:\n  /schliessen GOLD\n  /schliessen NATURAL_GAS\n  /schliessen ALLE               (fragt erst nach Bestätigung)\n  /schliessen ALLE BESTAETIGEN   (schließt wirklich alle)',
     'Usage: /close SYMBOL  or  /close ALL\nExamples:\n  /close GOLD\n  /close NATURAL_GAS\n  /close ALL           (asks for confirmation first)\n  /close ALL CONFIRM   (really closes all)',
     'Kullanım: /kapat SYMBOL  veya  /kapat HEPSI\nÖrnekler:\n  /kapat GOLD\n  /kapat NATURAL_GAS\n  /kapat HEPSI          (önce onay ister)\n  /kapat HEPSI ONAYLA   (gerçekten hepsini kapatır)'),
    ('⚠️ Bu komut {0} açık pozisyonun HEPSİNİ kapatacak!\nEmin isen: /kapat ALLE ONAYLA',
     '⚠️ Dieser Befehl schließt ALLE {0} offenen Positionen!\nWenn du sicher bist: /schliessen ALLE BESTAETIGEN',
     '⚠️ This command will close ALL {0} open positions!\nIf you are sure: /close ALL CONFIRM',
     '⚠️ Bu komut {0} açık pozisyonun HEPSİNİ kapatacak!\nEmin isen: /kapat HEPSI ONAYLA'),
    ('✅ {0} pozisyon kapatıldı. {1} hata.',
     '✅ {0} Positionen geschlossen. {1} Fehler.',
     '✅ {0} positions closed. {1} errors.',
     '✅ {0} pozisyon kapatıldı. {1} hata.'),
    ("⚠️ '{0}' bilinmiyor. Semboller: ",
     "⚠️ '{0}' unbekannt. Symbole: ",
     "⚠️ '{0}' unknown. Symbols: ",
     "⚠️ '{0}' bilinmiyor. Semboller: "),
    ('{0} icin acik pozisyon yok.',
     'Keine offene Position für {0}.',
     'No open position for {0}.',
     '{0} için açık pozisyon yok.'),
    ('✅ {0}: {1}/{2} pozisyon kapatıldı.',
     '✅ {0}: {1}/{2} Positionen geschlossen.',
     '✅ {0}: {1}/{2} positions closed.',
     '✅ {0}: {1}/{2} pozisyon kapatıldı.'),
    (' ({0} hata)',
     ' ({0} Fehler)',
     ' ({0} errors)',
     ' ({0} hata)'),
    ('📈 {0} | MA 9/26 SİNYALLERİ\n',
     '📈 {0} | MA 9/26 SIGNALE\n',
     '📈 {0} | MA 9/26 SIGNALS\n',
     '📈 {0} | MA 9/26 SİNYALLERİ\n'),
    ('🔍 Volatilite kontrolü yapılıyor...',
     '🔍 Volatilitätsprüfung läuft...',
     '🔍 Volatility check running...',
     '🔍 Volatilite kontrolü yapılıyor...'),
    ('✅ Tüm pozisyonlar normal aralıkta',
     '✅ Alle Positionen im normalen Bereich',
     '✅ All positions within normal range',
     '✅ Tüm pozisyonlar normal aralıkta'),
    ('📡 Spread tarama başlatılıyor...',
     '📡 Spread-Scan wird gestartet...',
     '📡 Starting spread scan...',
     '📡 Spread tarama başlatılıyor...'),
    ("✅ Spread'ler güncellendi:\n",
     '✅ Spreads aktualisiert:\n',
     '✅ Spreads updated:\n',
     "✅ Spread'ler güncellendi:\n"),
    ('\n... ve {0} daha',
     '\n... und {0} weitere',
     '\n... and {0} more',
     '\n... ve {0} daha'),
    ('⚠️ Spread verisi alınamadı.',
     '⚠️ Spread-Daten konnten nicht abgerufen werden.',
     '⚠️ Could not fetch spread data.',
     '⚠️ Spread verisi alınamadı.'),
    ('Kullanim: /backtest SYMBOL [GUN]\nOrnek: /backtest SILVER 200\nSemboller: ',
     'Verwendung: /backtest SYMBOL [TAGE]\nBeispiel: /backtest SILVER 200\nSymbole: ',
     'Usage: /backtest SYMBOL [DAYS]\nExample: /backtest SILVER 200\nSymbols: ',
     'Kullanım: /backtest SYMBOL [GÜN]\nÖrnek: /backtest SILVER 200\nSemboller: '),
    ('Backtest: {0} {1} gün - 3 zaman dilimi test ediliyor...',
     'Backtest: {0} {1} Tage - 3 Zeitrahmen werden getestet...',
     'Backtest: {0} {1} days - testing 3 timeframes...',
     'Backtest: {0} {1} gün - 3 zaman dilimi test ediliyor...'),
    ('Backtest hatası: {0}',
     'Backtest-Fehler: {0}',
     'Backtest error: {0}',
     'Backtest hatası: {0}'),
    ('Kullanim: /deepdive SYMBOL [RESOLUTION] [GUN]\nOrnek: /deepdive SILVER HOUR_4 30',
     'Verwendung: /deepdive SYMBOL [RESOLUTION] [TAGE]\nBeispiel: /deepdive SILVER HOUR_4 30',
     'Usage: /deepdive SYMBOL [RESOLUTION] [DAYS]\nExample: /deepdive SILVER HOUR_4 30',
     'Kullanım: /deepdive SYMBOL [RESOLUTION] [GÜN]\nÖrnek: /deepdive SILVER HOUR_4 30'),
    ('{0} {1} {2} gun cekiliyor...',
     '{0} {1} {2} Tage werden abgerufen...',
     'Fetching {0} {1} {2} days...',
     '{0} {1} {2} gün çekiliyor...'),
    ('Veri alinamadi: {0}',
     'Daten konnten nicht abgerufen werden: {0}',
     'Could not fetch data: {0}',
     'Veri alınamadı: {0}'),
    ('Ozet yok',
     'Keine Zusammenfassung',
     'No summary',
     'Özet yok'),
    ('\n⛔ DEPOT DD HALT: {0}',
     '\n⛔ DEPOT DD HALT: {0}',
     '\n⛔ ACCOUNT DD HALT: {0}',
     '\n⛔ HESAP DD HALT: {0}'),
    ('\n✅ Depot DD Normal | Peak: {0}EUR',
     '\n✅ Depot DD Normal | Peak: {0}EUR',
     '\n✅ Account DD normal | Peak: {0}EUR',
     '\n✅ Hesap DD normal | Peak: {0}EUR'),
    ('NEXUS QUANT STATS\nKorku/Açgözlülük: {0}/100 ({1})\nSonraki Olay: {2} ({3} gün){4}\n\nASSET PERFORMANSI:\n{5}\n\nSON 10 TRADE:\n{6}',
     'NEXUS QUANT STATS\nAngst/Gier: {0}/100 ({1})\nNächstes Ereignis: {2} ({3} Tage){4}\n\nASSET-PERFORMANCE:\n{5}\n\nLETZTE 10 TRADES:\n{6}',
     'NEXUS QUANT STATS\nFear/Greed: {0}/100 ({1})\nNext event: {2} ({3} days){4}\n\nASSET PERFORMANCE:\n{5}\n\nLAST 10 TRADES:\n{6}',
     'NEXUS QUANT STATS\nKorku/Açgözlülük: {0}/100 ({1})\nSonraki Olay: {2} ({3} gün){4}\n\nASSET PERFORMANSI:\n{5}\n\nSON 10 TRADE:\n{6}'),
    ('Bugun kayip yok.',
     'Heute keine Verluste.',
     'No losses today.',
     'Bugün kayıp yok.'),
    ('BUGUNUN KAYIP SAYACI ({0}):',
     'VERLUSTZÄHLER HEUTE ({0}):',
     "TODAY'S LOSS COUNTER ({0}):",
     'BUGÜNÜN KAYIP SAYACI ({0}):'),
    ('  BLOKLU {0}: {1}x kayip',
     '  GESPERRT {0}: {1}x Verlust',
     '  BLOCKED {0}: {1}x loss',
     '  BLOKLU {0}: {1}x kayıp'),
    ('📰 {0} | 14 günlük haber analizi yapılıyor ({1})...',
     '📰 {0} | Nachrichtenanalyse über 14 Tage läuft ({1})...',
     '📰 {0} | Running 14-day news analysis ({1})...',
     '📰 {0} | 14 günlük haber analizi yapılıyor ({1})...'),
    ('Genel Makro',
     'Makro allgemein',
     'General Macro',
     'Genel Makro'),
    ('❌ DB okuma hatası: {0}',
     '❌ DB-Lesefehler: {0}',
     '❌ DB read error: {0}',
     '❌ DB okuma hatası: {0}'),
    ("⚠️ {0} | DB'de henüz haber yok.\nÖnce /newscollect ile haber topla (saatte bir otomatik da toplanır).",
     '⚠️ {0} | Noch keine Nachrichten in der DB.\nSammle zuerst Nachrichten mit /news_sammeln (wird auch stündlich automatisch gesammelt).',
     '⚠️ {0} | No news in the DB yet.\nCollect news first with /newscollect (also collected automatically every hour).',
     "⚠️ {0} | DB'de henüz haber yok.\nÖnce /haber_topla ile haber topla (saatte bir otomatik da toplanır)."),
    ('Analiz üretilemedi.',
     'Analyse konnte nicht erstellt werden.',
     'Analysis could not be generated.',
     'Analiz üretilemedi.'),
    ('⚠️ Gemini analiz hatası: {0}\n\n{1}',
     '⚠️ Gemini-Analysefehler: {0}\n\n{1}',
     '⚠️ Gemini analysis error: {0}\n\n{1}',
     '⚠️ Gemini analiz hatası: {0}\n\n{1}'),
    ('🔄 {0} | Haber toplama başlatılıyor (RSS + GDELT)...',
     '🔄 {0} | Nachrichtensammlung wird gestartet (RSS + GDELT)...',
     '🔄 {0} | Starting news collection (RSS + GDELT)...',
     '🔄 {0} | Haber toplama başlatılıyor (RSS + GDELT)...'),
    ('✅ {0} | Haber toplama tamamlandı:\n  RSS: {1} haber\n  GDELT: {2} haber\n  DB: 14 günlük birikim aktif',
     '✅ {0} | Nachrichtensammlung abgeschlossen:\n  RSS: {1} Nachrichten\n  GDELT: {2} Nachrichten\n  DB: 14-Tage-Archiv aktiv',
     '✅ {0} | News collection complete:\n  RSS: {1} news items\n  GDELT: {2} news items\n  DB: 14-day archive active',
     '✅ {0} | Haber toplama tamamlandı:\n  RSS: {1} haber\n  GDELT: {2} haber\n  DB: 14 günlük birikim aktif'),
    ('❌ Hata: {0}',
     '❌ Fehler: {0}',
     '❌ Error: {0}',
     '❌ Hata: {0}'),
    ('🧹 {0} | DB Temizlendi:\n  {1} eski haber silindi\n  {2} eski X post silindi\n  Artık /newscollect ile güncel haber topla',
     '🧹 {0} | DB bereinigt:\n  {1} alte Nachrichten gelöscht\n  {2} alte X-Posts gelöscht\n  Sammle jetzt mit /news_sammeln aktuelle Nachrichten',
     '🧹 {0} | DB cleaned:\n  {1} old news items deleted\n  {2} old X posts deleted\n  Now collect fresh news with /newscollect',
     '🧹 {0} | DB Temizlendi:\n  {1} eski haber silindi\n  {2} eski X post silindi\n  Artık /haber_topla ile güncel haber topla'),
    ('❌ DB temizleme hatası: {0}',
     '❌ Fehler bei der DB-Bereinigung: {0}',
     '❌ DB cleanup error: {0}',
     '❌ DB temizleme hatası: {0}'),
    ('⚠️ Usage: /manuell SYMBOL SIDE SIZE [SL] [TP]\nBeispiele:\n  /manuell GOLD BUY 100\n  /manuell SILVER SELL 200 30.5 35.0\n  /manuell NATURAL_GAS BUY 50',
     '⚠️ Usage: /manuell SYMBOL SIDE SIZE [SL] [TP]\nBeispiele:\n  /manuell GOLD BUY 100\n  /manuell SILVER SELL 200 30.5 35.0\n  /manuell NATURAL_GAS BUY 50',
     '⚠️ Usage: /manual SYMBOL SIDE SIZE [SL] [TP]\nExamples:\n  /manual GOLD BUY 100\n  /manual SILVER SELL 200 30.5 35.0\n  /manual NATURAL_GAS BUY 50',
     '⚠️ Kullanım: /manuel SYMBOL SIDE SIZE [SL] [TP]\nÖrnekler:\n  /manuel GOLD BUY 100\n  /manuel SILVER SELL 200 30.5 35.0\n  /manuel NATURAL_GAS BUY 50'),
    ('⚠️ SIDE muss BUY oder SELL sein, nicht: {0}',
     '⚠️ SIDE muss BUY oder SELL sein, nicht: {0}',
     '⚠️ SIDE must be BUY or SELL, not: {0}',
     '⚠️ SIDE, BUY veya SELL olmalı, şu olamaz: {0}'),
    ('⚠️ SIZE muss eine Zahl sein: {0}',
     '⚠️ SIZE muss eine Zahl sein: {0}',
     '⚠️ SIZE must be a number: {0}',
     '⚠️ SIZE bir sayı olmalı: {0}'),
    ("⚠️ Symbol '{0}' nicht in MARKET_CONFIG.\nVerfügbar: {1}",
     "⚠️ Symbol '{0}' nicht in MARKET_CONFIG.\nVerfügbar: {1}",
     "⚠️ Symbol '{0}' not in MARKET_CONFIG.\nAvailable: {1}",
     "⚠️ '{0}' sembolü MARKET_CONFIG içinde yok.\nMevcut: {1}"),
    ('❌ API Verbindung fehlgeschlagen',
     '❌ API Verbindung fehlgeschlagen',
     '❌ API connection failed',
     '❌ API bağlantısı başarısız'),
    ('❌ Preis konnte nicht geholt werden: HTTP {0}',
     '❌ Preis konnte nicht geholt werden: HTTP {0}',
     '❌ Could not fetch price: HTTP {0}',
     '❌ Fiyat alınamadı: HTTP {0}'),
    ('❌ Ungültiger Preis',
     '❌ Ungültiger Preis',
     '❌ Invalid price',
     '❌ Geçersiz fiyat'),
    ('❌ Preis-Fehler: {0}',
     '❌ Preis-Fehler: {0}',
     '❌ Price error: {0}',
     '❌ Fiyat hatası: {0}'),
    ('⚠️ SL/TP müssen Zahlen sein',
     '⚠️ SL/TP müssen Zahlen sein',
     '⚠️ SL/TP must be numbers',
     '⚠️ SL/TP sayı olmalı'),
    ('❌ Size-Berechnung fehlgeschlagen: {0}',
     '❌ Size-Berechnung fehlgeschlagen: {0}',
     '❌ Size calculation failed: {0}',
     '❌ Büyüklük hesaplaması başarısız: {0}'),
    ('⚡ MANUELLER TRADE wird ausgeführt:\nSymbol: {0}\nSeite: {1}\nGröße: {2}€ ({3} units)\nPreis: {4}\nSL: {5}\nTP: {6}',
     '⚡ MANUELLER TRADE wird ausgeführt:\nSymbol: {0}\nSeite: {1}\nGröße: {2}€ ({3} units)\nPreis: {4}\nSL: {5}\nTP: {6}',
     '⚡ MANUAL TRADE is being executed:\nSymbol: {0}\nSide: {1}\nSize: {2}€ ({3} units)\nPrice: {4}\nSL: {5}\nTP: {6}',
     '⚡ MANUEL İŞLEM gerçekleştiriliyor:\nSembol: {0}\nYön: {1}\nBüyüklük: {2}€ ({3} birim)\nFiyat: {4}\nSL: {5}\nTP: {6}'),
    ('✅ MANUELLER TRADE eröffnet!\nSymbol: {0} {1}\nGröße: {2} units ({3}€)\nEntry: {4}\nSL: {5} | TP: {6}\nPyramiding-Stufe: 1',
     '✅ MANUELLER TRADE eröffnet!\nSymbol: {0} {1}\nGröße: {2} units ({3}€)\nEntry: {4}\nSL: {5} | TP: {6}\nPyramiding-Stufe: 1',
     '✅ MANUAL TRADE opened!\nSymbol: {0} {1}\nSize: {2} units ({3}€)\nEntry: {4}\nSL: {5} | TP: {6}\nPyramiding level: 1',
     '✅ MANUEL İŞLEM açıldı!\nSembol: {0} {1}\nBüyüklük: {2} birim ({3}€)\nGiriş: {4}\nSL: {5} | TP: {6}\nPyramiding seviyesi: 1'),
    ('❌ Trade fehlgeschlagen: {0}',
     '❌ Trade fehlgeschlagen: {0}',
     '❌ Trade failed: {0}',
     '❌ İşlem başarısız: {0}'),
    ('✅ Aktif HARD BLOCK yok. Tum assetler serbest.',
     '✅ Kein aktiver HARD BLOCK (Handelssperre). Alle Assets sind frei.',
     '✅ No active HARD BLOCK. All assets are free.',
     '✅ Aktif HARD BLOCK yok. Tüm assetler serbest.'),
    ('🔒 AKTİF HARD BLOKLAR:',
     '🔒 AKTIVE HARD BLOCKS (Handelssperren):',
     '🔒 ACTIVE HARD BLOCKS:',
     '🔒 AKTİF HARD BLOKLAR:'),
    ("\nKaldirmak icin: '<asset> serbest' veya '<asset> freigeben'",
     "\nZum Aufheben: '<asset> serbest' oder '<asset> freigeben'",
     "\nTo remove: '<asset> serbest' or '<asset> freigeben'",
     "\nKaldırmak için: '<asset> serbest' veya '<asset> freigeben'"),
    (' adet kullanici notu silindi. Gemini artik bunlari gormeyecek.',
     ' Benutzernotizen gelöscht. Gemini sieht sie ab jetzt nicht mehr.',
     ' user notes deleted. Gemini will no longer see them.',
     ' adet kullanıcı notu silindi. Gemini artık bunları görmeyecek.'),
    ('Silme hatasi: ',
     'Fehler beim Löschen: ',
     'Delete error: ',
     'Silme hatası: '),
    ('⛔ Yetkisiz erişim.',
     '⛔ Unbefugter Zugriff.',
     '⛔ Unauthorized access.',
     '⛔ Yetkisiz erişim.'),
    ('✅ HARD BLOCK kaldirildi: {0} artik serbest.',
     '✅ HARD BLOCK (Handelssperre) aufgehoben: {0} ist jetzt frei.',
     '✅ HARD BLOCK removed: {0} is now free.',
     '✅ HARD BLOCK kaldırıldı: {0} artık serbest.'),
    ('ℹ️ {0} zaten bloklu degildi.',
     'ℹ️ {0} war ohnehin nicht gesperrt.',
     'ℹ️ {0} was not blocked anyway.',
     'ℹ️ {0} zaten bloklu değildi.'),
    ('⛔ HARD BLOCK aktif: {0} ({1}) — Gemini bu karari override EDEMEZ!',
     '⛔ HARD BLOCK (Handelssperre) aktiv: {0} ({1}) — Gemini KANN diese Entscheidung NICHT übersteuern!',
     '⛔ HARD BLOCK active: {0} ({1}) — Gemini CANNOT override this decision!',
     '⛔ HARD BLOCK aktif: {0} ({1}) — Gemini bu kararı override EDEMEZ!'),
    ('✅ {0} adet {1} pozisyonu kapatildi.',
     '✅ {0} {1}-Position(en) geschlossen.',
     '✅ {0} {1} position(s) closed.',
     '✅ {0} adet {1} pozisyonu kapatıldı.'),
    ('ℹ️ {0} icin acik pozisyon bulunamadi.',
     'ℹ️ Keine offene Position für {0} gefunden.',
     'ℹ️ No open position found for {0}.',
     'ℹ️ {0} için açık pozisyon bulunamadı.'),
    ('⚠️ Pozisyon kapatirken hata: {0}',
     '⚠️ Fehler beim Schließen der Position: {0}',
     '⚠️ Error while closing position: {0}',
     '⚠️ Pozisyon kapatırken hata: {0}'),
    ('🔒 Aktif bloklar: {0}',
     '🔒 Aktive Sperren: {0}',
     '🔒 Active blocks: {0}',
     '🔒 Aktif bloklar: {0}'),
    ('Notun kaydedildi. Bir sonraki analizde (maks 30 dk) Gemini kullanacak. Quota harcanmadi.',
     'Deine Notiz wurde gespeichert. Gemini nutzt sie bei der nächsten Analyse (max. 30 min). Kein Quota verbraucht.',
     'Your note has been saved. Gemini will use it in the next analysis (max 30 min). No quota used.',
     'Notun kaydedildi. Bir sonraki analizde (maks 30 dk) Gemini kullanacak. Quota harcanmadı.'),
    ('Kayit hatasi: ',
     'Fehler beim Speichern: ',
     'Save error: ',
     'Kayıt hatası: '),
    ('vom Bot oder von Hand geschlossen',
     'vom Bot oder von Hand geschlossen',
     'closed by the bot or manually',
     'bot tarafından veya elle kapatıldı'),
    ('Broker (Händler)',
     'Broker (Händler)',
     'Broker (dealer)',
     'Broker (işlem masası)'),
    ('Broker (Margin-Glattstellung)',
     'Broker (Margin-Glattstellung)',
     'Broker (margin close-out)',
     'Broker (marjin kapatması)'),
    ('Broker (System)',
     'Broker (System)',
     'Broker (system)',
     'Broker (sistem)'),
    ('⚪ POSITION GESCHLOSSEN: {0} ({1})',
     '⚪ POSITION GESCHLOSSEN: {0} ({1})',
     '⚪ POSITION CLOSED: {0} ({1})',
     '⚪ POZİSYON KAPATILDI: {0} ({1})'),
    ('Grund: in der Capital.com-Historie nicht gefunden',
     'Grund: in der Capital.com-Historie nicht gefunden',
     'Reason: not found in the Capital.com history',
     'Neden: Capital.com geçmişinde bulunamadı'),
    ('Einstieg {0} | Größe {1}',
     'Einstieg {0} | Größe {1}',
     'Entry {0} | Size {1}',
     'Giriş {0} | Büyüklük {1}'),
    ('nicht ermittelbar',
     'nicht ermittelbar',
     'cannot be determined',
     'belirlenemiyor'),
    (' (aus den Kursen gerechnet, ohne Gebühren)',
     ' (aus den Kursen gerechnet, ohne Gebühren)',
     ' (calculated from the prices, excluding fees)',
     ' (fiyatlardan hesaplandı, ücretler hariç)'),
    ('{0} Geschlossen (Bot/Hand): {1} {2} | {3} → {4} | Größe {5} | Ergebnis {6}',
     '{0} Geschlossen (Bot/Hand): {1} {2} | {3} → {4} | Größe {5} | Ergebnis {6}',
     '{0} Closed (bot/manual): {1} {2} | {3} → {4} | Size {5} | Result {6}',
     '{0} Kapatıldı (bot/elle): {1} {2} | {3} → {4} | Büyüklük {5} | Sonuç {6}'),
    ('{0} POSITION GESCHLOSSEN: {1} ({2})',
     '{0} POSITION GESCHLOSSEN: {1} ({2})',
     '{0} POSITION CLOSED: {1} ({2})',
     '{0} POZİSYON KAPATILDI: {1} ({2})'),
    ('Einstieg {0} → Ausstieg {1} | Größe {2}',
     'Einstieg {0} → Ausstieg {1} | Größe {2}',
     'Entry {0} → Exit {1} | Size {2}',
     'Giriş {0} → Çıkış {1} | Büyüklük {2}'),
    ('Heute {0}. Stop-Loss-Verlust bei {1}',
     'Heute {0}. Stop-Loss-Verlust bei {1}',
     'Stop Loss loss no. {0} today on {1}',
     'Bugün {0}. Stop Loss kaybı: {1}'),
    (' (ab {0} für heute gesperrt)',
     ' (ab {0} für heute gesperrt)',
     ' (locked for today from {0})',
     ' ({0} itibarıyla bugün için kilitli)'),
    ('Stop am Einstieg (Breakeven) - zählt nicht als Verlust.',
     'Stop am Einstieg (Breakeven) - zählt nicht als Verlust.',
     'Stop at entry (Breakeven) - does not count as a loss.',
     'Stop girişte (Breakeven) - kayıp sayılmaz.'),
    ('Der Stop lag am Einstieg oder im Gewinn (Breakeven / Trailing).',
     'Der Stop lag am Einstieg oder im Gewinn (Breakeven / Trailing).',
     'The stop was at entry or in profit (Breakeven / Trailing).',
     'Stop girişte veya kârdaydı (Breakeven / Trailing).'),
    ('🔔 İşlem Bildirimi:\n{0}',
     '🔔 Handelsmeldung:\n{0}',
     '🔔 Trade notification:\n{0}',
     '🔔 İşlem Bildirimi:\n{0}'),
    ('🔔 Scan ohne neuen Trade:\n{0}',
     '🔔 Scan ohne neuen Trade:\n{0}',
     '🔔 Scan without new trade:\n{0}',
     '🔔 Yeni işlem olmadan tarama:\n{0}'),
    ('INFO {0} | Gemini quota doldu → Groq ile devam ediliyor',
     'INFO {0} | Gemini-Quota erschöpft → weiter mit Groq',
     'INFO {0} | Gemini quota exhausted → continuing with Groq',
     'INFO {0} | Gemini quota doldu → Groq ile devam ediliyor'),
    ('Cihat: Signal-Wechsel ({0}→{1})',
     'Cihat: Signal-Wechsel ({0}→{1})',
     'Cihat: signal change ({0}→{1})',
     'Cihat: sinyal değişimi ({0}→{1})'),
    ('Rogers: News negativ ({0})',
     'Rogers: News negativ ({0})',
     'Rogers: news negative ({0})',
     'Rogers: haberler negatif ({0})'),
    ('Taleb: Extreme negative News',
     'Taleb: Extreme negative News',
     'Taleb: extremely negative news',
     'Taleb: aşırı negatif haberler'),
    ('Soros: Momentum verloren',
     'Soros: Momentum verloren',
     'Soros: momentum lost',
     'Soros: momentum kayboldu'),
    ('🔍 EXIT-EMPFEHLUNG: {0}\nRichtung: {1}\nExit-Stimmen: {2}/5\nGründe:\n',
     '🔍 EXIT-EMPFEHLUNG: {0}\nRichtung: {1}\nExit-Stimmen: {2}/5\nGründe:\n',
     '🔍 EXIT RECOMMENDATION: {0}\nDirection: {1}\nExit votes: {2}/5\nReasons:\n',
     '🔍 ÇIKIŞ ÖNERİSİ: {0}\nYön: {1}\nÇıkış oyları: {2}/5\nNedenler:\n'),
    ('\nNeues Signal: {0}\n',
     '\nNeues Signal: {0}\n',
     '\nNew signal: {0}\n',
     '\nYeni sinyal: {0}\n'),
    ('News-Sentiment: {0}\n\n',
     'News-Sentiment: {0}\n\n',
     'News sentiment: {0}\n\n',
     'Haber duyarlılığı: {0}\n\n'),
    ('⚡ AUTO-EXIT wird ausgeführt...',
     '⚡ AUTO-EXIT wird ausgeführt...',
     '⚡ AUTO-EXIT is being executed...',
     '⚡ OTOMATİK ÇIKIŞ gerçekleştiriliyor...'),
    ('✅ {0} geschlossen',
     '✅ {0} geschlossen',
     '✅ {0} closed',
     '✅ {0} kapatıldı'),
    (' Fehler beim Schließen: {0}',
     ' Fehler beim Schließen: {0}',
     ' Error while closing: {0}',
     ' Kapatma hatası: {0}'),
    ('⏸️ Manuelle Bestätigung erforderlich\n',
     '⏸️ Manuelle Bestätigung erforderlich\n',
     '⏸️ Manual confirmation required\n',
     '⏸️ Manuel onay gerekli\n'),
    ("Sende 'exit <SYMBOL>' zum Schließen",
     "Sende 'exit <SYMBOL>' zum Schließen",
     "Send 'exit <SYMBOL>' to close",
     "Kapatmak için 'exit <SYMBOL>' gönder"),
    ('✅ Ja, verkaufen',
     '✅ Ja, verkaufen',
     '✅ Yes, sell',
     '✅ Evet, sat'),
    ('❌ Nein, weiter',
     '❌ Nein, weiter',
     '❌ No, continue',
     '❌ Hayır, devam'),
    ('🎯 TÄGLICHES ATR-ZIEL ERREICHT ({0}-Tage)\n{1} ({2})\n\nEinstieg: {3}\nAktuell: {4}\nGewinn (Preis): +{5}\nGewinn (EUR): {6}\n\nØ-Tagesbewegung ({7}T): {8} (%{9})\nZiel (%{10} davon): {11}\n\nWillst du jetzt verkaufen?',
     '🎯 TÄGLICHES ATR-ZIEL ERREICHT ({0}-Tage)\n{1} ({2})\n\nEinstieg: {3}\nAktuell: {4}\nGewinn (Preis): +{5}\nGewinn (EUR): {6}\n\nØ-Tagesbewegung ({7}T): {8} (%{9})\nZiel (%{10} davon): {11}\n\nWillst du jetzt verkaufen?',
     '🎯 DAILY ATR TARGET REACHED ({0}-day)\n{1} ({2})\n\nEntry: {3}\nCurrent: {4}\nProfit (price): +{5}\nProfit (EUR): {6}\n\nØ daily move ({7}d): {8} ({9}%)\nTarget ({10}% of it): {11}\n\nDo you want to sell now?',
     '🎯 GÜNLÜK ATR HEDEFİNE ULAŞILDI ({0} günlük)\n{1} ({2})\n\nGiriş: {3}\nGüncel: {4}\nKâr (fiyat): +{5}\nKâr (EUR): {6}\n\nØ günlük hareket ({7}g): {8} (%{9})\nHedef (bunun %{10} kadarı): {11}\n\nŞimdi satmak istiyor musun?'),
    ('Ungueltige Anfrage',
     'Ungueltige Anfrage',
     'Invalid request',
     'Geçersiz istek'),
    ('Position geschlossen',
     'Position geschlossen',
     'Position closed',
     'Pozisyon kapatıldı'),
    ('\n\n>> VERKAUFT (auf deine Bestätigung hin)',
     '\n\n>> VERKAUFT (auf deine Bestätigung hin)',
     '\n\n>> SOLD (upon your confirmation)',
     '\n\n>> SATILDI (senin onayınla)'),
    ('Fehler beim Schließen ({0})',
     'Fehler beim Schließen ({0})',
     'Error while closing ({0})',
     'Kapatma hatası ({0})'),
    ('Position läuft weiter',
     'Position läuft weiter',
     'Position keeps running',
     'Pozisyon devam ediyor'),
    ('\n\n>> WEITER (normale Logik läuft unverändert)',
     '\n\n>> WEITER (normale Logik läuft unverändert)',
     '\n\n>> CONTINUE (normal logic runs unchanged)',
     '\n\n>> DEVAM (normal mantık değişmeden çalışıyor)'),
    ('⚠️ NEXUS NATURE v12.0: API bağlantı hatası! Yeniden deneniyor... (Döngü #{0})',
     '⚠️ NEXUS NATURE v12.0: API-Verbindungsfehler! Neuer Versuch... (Durchlauf #{0})',
     '⚠️ NEXUS NATURE v12.0: API connection error! Retrying... (cycle #{0})',
     '⚠️ NEXUS NATURE v12.0: API bağlantı hatası! Yeniden deneniyor... (Döngü #{0})'),
    ('🔄 Piramiding Düzeltme:\n{0}',
     '🔄 Pyramiding-Korrektur:\n{0}',
     '🔄 Pyramiding correction:\n{0}',
     '🔄 Piramiding Düzeltme:\n{0}'),
    ('DEPOT DD ALARMI! Bugun yeni trade YOK.\n',
     'DEPOT-DD-ALARM! Heute KEIN neuer Trade.\n',
     'ACCOUNT DD ALARM! NO new trade today.\n',
     'DEPOT DD ALARMI! Bugün yeni trade YOK.\n'),
    ('🎯 {0} — Trading pausiert bis morgen',
     '🎯 {0} — Trading pausiert bis morgen',
     '🎯 {0} — trading paused until tomorrow',
     '🎯 {0} — işlemler yarına kadar duraklatıldı'),
    ('🛑 {0} — Trading gestoppt!',
     '🛑 {0} — Trading gestoppt!',
     '🛑 {0} — trading stopped!',
     '🛑 {0} — işlemler durduruldu!'),
    ('FALLBACK: Gate-Keeper 0 aday - bu dongude islem yok (KI cagrilmadi)',
     'FALLBACK: Gate-Keeper 0 Kandidaten - kein Trade in diesem Durchlauf (KI nicht aufgerufen)',
     'FALLBACK: Gate-Keeper 0 candidates - no trade in this cycle (AI not called)',
     'FALLBACK: Gate-Keeper 0 aday - bu döngüde işlem yok (KI çağrılmadı)'),
    ('🟢 {0} | NEXUS NATURE v12.0 Tarama #{1} tamamlandı.\nBu döngüde trade sinyali yok.\nPiyasa izlenmeye devam ediyor.',
     '🟢 {0} | NEXUS NATURE v12.0 Scan #{1} abgeschlossen.\nKein Trade-Signal in diesem Durchlauf.\nDer Markt wird weiter beobachtet.',
     '🟢 {0} | NEXUS NATURE v12.0 scan #{1} completed.\nNo trade signal in this cycle.\nStill monitoring the market.',
     '🟢 {0} | NEXUS NATURE v12.0 Tarama #{1} tamamlandı.\nBu döngüde trade sinyali yok.\nPiyasa izlenmeye devam ediyor.'),
    ('  {0} {1} UPL:{2} Seviye:{3}\n',
     '  {0} {1} UPL:{2} Stufe:{3}\n',
     '  {0} {1} UPL:{2} Level:{3}\n',
     '  {0} {1} UPL:{2} Seviye:{3}\n'),
    ('TRADE SONRASI DEPO:\nNakit: {0} EUR | Musait: {1} EUR ({2}%) | UPL: {3} EUR\nPozisyonlar ({4}):\n{5}',
     'DEPOT NACH DEM TRADE:\nKontostand: {0} EUR | Verfügbar: {1} EUR ({2}%) | UPL: {3} EUR\nPositionen ({4}):\n{5}',
     'ACCOUNT AFTER TRADE:\nBalance: {0} EUR | Available: {1} EUR ({2}%) | UPL: {3} EUR\nPositions ({4}):\n{5}',
     'TRADE SONRASI DEPO:\nNakit: {0} EUR | Müsait: {1} EUR ({2}%) | UPL: {3} EUR\nPozisyonlar ({4}):\n{5}'),
    ('📊 Pyramiding Özet:\n',
     '📊 Pyramiding-Übersicht:\n',
     '📊 Pyramiding summary:\n',
     '📊 Pyramiding Özet:\n'),
    ('• {0}: Seviye {1} (aktif)\n',
     '• {0}: Stufe {1} (aktiv)\n',
     '• {0}: Level {1} (active)\n',
     '• {0}: Seviye {1} (aktif)\n'),
    ('  ℹ️  TRADING_ASSETS nicht in .env → alle aus capital_markets_config.py: {0}',
     '  ℹ️  TRADING_ASSETS nicht in .env → alle aus capital_markets_config.py: {0}',
     '  ℹ️  TRADING_ASSETS not in .env → all from capital_markets_config.py: {0}',
     '  ℹ️  TRADING_ASSETS .env içinde yok → hepsi capital_markets_config.py dosyasından: {0}'),
    ('❌ GEMINI_MODEL_1 eksik! .env dosyasına GEMINI_MODEL_1=gemini-3.5-flash ekle.',
     '❌ GEMINI_MODEL_1 fehlt! Trage GEMINI_MODEL_1=gemini-3.5-flash in die .env-Datei ein.',
     '❌ GEMINI_MODEL_1 missing! Add GEMINI_MODEL_1=gemini-3.5-flash to the .env file.',
     '❌ GEMINI_MODEL_1 eksik! .env dosyasına GEMINI_MODEL_1=gemini-3.5-flash ekle.'),
    ('✅ Gemini modeller: {0}{1}',
     '✅ Gemini-Modelle: {0}{1}',
     '✅ Gemini models: {0}{1}',
     '✅ Gemini modeller: {0}{1}'),
    ('❌ GEMINI_KEYS eksik! .env dosyasına GEMINI_KEYS=key1,key2 ekle.',
     '❌ GEMINI_KEYS fehlt! Trage GEMINI_KEYS=key1,key2 in die .env-Datei ein.',
     '❌ GEMINI_KEYS missing! Add GEMINI_KEYS=key1,key2 to the .env file.',
     '❌ GEMINI_KEYS eksik! .env dosyasına GEMINI_KEYS=key1,key2 ekle.'),
    ('✅ Gemini keys: {0} adet',
     '✅ Gemini-Keys: {0} Stück',
     '✅ Gemini keys: {0} total',
     '✅ Gemini keys: {0} adet'),
    ('⚠️ GROQ_KEYS yok (opsiyonel fallback)',
     '⚠️ GROQ_KEYS fehlt (optionaler Fallback)',
     '⚠️ GROQ_KEYS missing (optional fallback)',
     '⚠️ GROQ_KEYS yok (opsiyonel fallback)'),
    ('Provider sırası: {0}',
     'Provider-Reihenfolge: {0}',
     'Provider order: {0}',
     'Provider sırası: {0}'),
    ('\n\n🔧 Konfig:\n',
     '\n\n🔧 Konfig:\n',
     '\n\n🔧 Config:\n',
     '\n\n🔧 Konfig:\n'),
    ('Başlangıç Senkronu:\n{0}',
     'Start-Synchronisierung:\n{0}',
     'Startup sync:\n{0}',
     'Başlangıç Senkronu:\n{0}'),
    ('Minutenlimit',
     'Minutenlimit',
     'per-minute limit',
     'dakikalık limit'),
    ('  Hata: {0}',
     '  Fehler: {0}',
     '  Error: {0}',
     '  Hata: {0}'),
    ('Hata: {0}',
     'Fehler: {0}',
     'Error: {0}',
     'Hata: {0}'),
    ('Fehler: {0}',
     'Fehler: {0}',
     'Error: {0}',
     'Hata: {0}'),
    ('Fehler: ',
     'Fehler: ',
     'Error: ',
     'Hata: '),
    (' degisim)',
     ' Änderung)',
     ' change)',
     ' değişim)'),
    ('{0} bulunamadi.',
     '{0} nicht gefunden.',
     '{0} not found.',
     '{0} bulunamadı.'),
    ('     Sebep: {0}',
     '     Grund: {0}',
     '     Reason: {0}',
     '     Sebep: {0}'),
    ('Grund: {0}',
     'Grund: {0}',
     'Reason: {0}',
     'Neden: {0}'),
    ('Ergebnis: {0}',
     'Ergebnis: {0}',
     'Result: {0}',
     'Sonuç: {0}'),
    ('\nGrund:\n{0}',
     '\nGrund:\n{0}',
     '\nReason:\n{0}',
     '\nNeden:\n{0}'),
    ('  Yok',
     '  Keine',
     '  None',
     '  Yok'),
    ('Belirsiz',
     'Unklar',
     'Unclear',
     'Belirsiz'),
    ('limit {0}/Tag',
     'limit {0}/Tag',
     'limit {0}/day',
     'limit {0}/gün'),
    ('🔎 Diagnose läuft ({0} Tage) ... das dauert bis zu einer Minute.',
     '🔎 Diagnose läuft ({0} Tage) ... das dauert bis zu einer Minute.',
     '🔎 Diagnosis running ({0} days) ... this takes up to a minute.',
     '🔎 Teşhis çalışıyor ({0} gün) ... bir dakika kadar sürer.'),
    ('🔎 Diagnose läuft schon - bitte warten.',
     '🔎 Diagnose läuft schon - bitte warten.',
     '🔎 A diagnosis is already running - please wait.',
     '🔎 Teşhis zaten çalışıyor - lütfen bekle.'),
    ('⚠️ nexus_diagnose.py fehlt im Bot-Ordner - Diagnose nicht möglich.',
     '⚠️ nexus_diagnose.py fehlt im Bot-Ordner - Diagnose nicht möglich.',
     '⚠️ nexus_diagnose.py is missing in the bot folder - no diagnosis possible.',
     '⚠️ nexus_diagnose.py bot klasöründe yok - teşhis yapılamıyor.'),
    ('⚠️ Diagnose fehlgeschlagen: {0}',
     '⚠️ Diagnose fehlgeschlagen: {0}',
     '⚠️ Diagnosis failed: {0}',
     '⚠️ Teşhis başarısız: {0}'),
    ('⚠️ Diagnose abgebrochen: nach {0} Sekunden nicht fertig.',
     '⚠️ Diagnose abgebrochen: nach {0} Sekunden nicht fertig.',
     '⚠️ Diagnosis aborted: not finished after {0} seconds.',
     '⚠️ Teşhis iptal edildi: {0} saniyede bitmedi.'),
    ('Vollständiger Diagnose-Bericht (auf Deutsch)',
     'Vollständiger Diagnose-Bericht (auf Deutsch)',
     'Full diagnosis report (in German)',
     'Tam teşhis raporu (Almanca)'),
]


# ---------------------------------------------------------------------------
# Uebersetzer
# ---------------------------------------------------------------------------
_IDX = {"de": 1, "en": 2, "tr": 3}
_PH = re.compile(r"\{(\d+)\}")
_compiled = {}          # sprache -> [(regex, reihenfolge der platzhalter, zieltext)]
_missing = set()
MISSING_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "nexus_lang_missing.log")


def _unbrace(s):
    return s.replace("{{", "{").replace("}}", "}")


def _compile(lang):
    regeln = []
    for rule in RULES:
        src, tgt = rule[0], rule[_IDX[lang]]
        if tgt == src:
            continue
        teile = _PH.split(src)                      # text, nr, text, nr, ... , text
        literal = "".join(teile[0::2])
        if len(re.findall(r"[^\W\d_]", literal)) < 3:
            continue                                # zu wenig fester Text - wuerde ueberall passen
        rx, order = "", []
        for i, t in enumerate(teile):
            if i % 2 == 0:
                rx += re.escape(_unbrace(t))
            else:
                order.append(int(t))
                letzter = (i == len(teile) - 2 and teile[-1] == "")
                rx += "([^\\n]*)" if letzter else "([^\\n]*?)"
        if not order and len(literal.strip()) < 14:
            # kurzer fester Text: nur als ganzes Wort / ganze Wortgruppe ersetzen
            # Grenze nur dort, wo der Text selbst mit einem Buchstaben anfaengt / aufhoert
            # ("Kayit hatasi: " endet auf ein Leerzeichen - danach DARF ein Wort folgen)
            kern = _unbrace(literal)
            if re.match(r"[^\W\d_]", kern[:1] or " "):
                rx = r"(?<![^\W\d_])" + rx
            if re.match(r"[^\W\d_]", kern[-1:] or " "):
                rx = rx + r"(?![^\W\d_])"
        regeln.append((len(literal), re.compile(rx), order, tgt))
    regeln.sort(key=lambda r: -r[0])                # laengster fester Text zuerst
    return [(r[1], r[2], r[3]) for r in regeln]


def _ersetzer(order, tgt):
    def f(m):
        try:
            args = [""] * (max(order) + 1 if order else 0)
            for k, nr in enumerate(order):
                args[nr] = m.group(k + 1)
            return tgt.format(*args)
        except Exception:
            return m.group(0)
    return f


def translate(text, lang):
    """Text in die Sprache uebersetzen. Unbekannte Teile bleiben, wie sie sind."""
    if lang not in _IDX or not isinstance(text, str) or not text:
        return text
    if lang not in _compiled:
        _compiled[lang] = _compile(lang)
    out, treffer = text, 0
    for rx, order, tgt in _compiled[lang]:
        out, n = rx.subn(_ersetzer(order, tgt), out)
        treffer += n
    if treffer == 0:
        _note_missing(text, lang)
    return out


def _note_missing(text, lang):
    """Texte merken, fuer die es keine Regel gab (zum Nachtragen). Nie mehr als 400 Zeilen."""
    kurz = " ".join(text.split())[:160]
    if len(re.findall(r"[^\W\d_]{3,}", kurz)) < 2 or kurz.startswith("TRADE:"):
        return
    key = (lang, re.sub(r"\d+(?:[.,]\d+)?", "#", kurz))
    if key in _missing or len(_missing) >= 400:
        return
    _missing.add(key)
    try:
        with open(MISSING_FILE, "a", encoding="utf-8") as f:
            f.write("%s | %s\n" % (lang, kurz))
    except Exception:
        pass


def selfcheck():
    """Platzhalter aller Regeln pruefen. Rueckgabe: Liste von Fehlertexten."""
    fehler = []
    for n, rule in enumerate(RULES):
        if len(rule) != 4:
            fehler.append("Regel %d: braucht 4 Texte (Quelle, de, en, tr)" % n)
            continue
        soll = sorted(_PH.findall(rule[0]))
        for lang, i in _IDX.items():
            if sorted(_PH.findall(rule[i])) != soll:
                fehler.append("Regel %d (%s): Platzhalter stimmen nicht: %r" % (n, lang, rule[i][:60]))
            try:
                rule[i].format(*["x"] * (len(soll) + 1))
            except Exception as e:
                fehler.append("Regel %d (%s): %s" % (n, lang, e))
    for lang in LANGS:
        for name, _ in menu_commands(lang):
            if not re.fullmatch(r"[a-z0-9_]{1,32}", name):
                fehler.append("Befehlsname %r (%s): nur a-z, 0-9, _ erlaubt" % (name, lang))
    return fehler


if __name__ == "__main__":
    if len(sys.argv) >= 3:
        print(translate(sys.argv[2].replace("\\n", "\n"), sys.argv[1]))
    else:
        f = selfcheck()
        print("%d Regeln, %d Befehle, Sprachen: %s" % (len(RULES), len(COMMANDS), ", ".join(LANGS)))
        print("\n".join(f) if f else "OK - alle Platzhalter stimmen")
        sys.exit(1 if f else 0)
