name: Sync selected files

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Prepare files
        run: |
          rm -rf public
          mkdir public
          cp mentor_name.txt public/
          cp toplam_egitim.txt public/
          cp NewsVerlage.txt public/
          cp Bot_egitim_videolari.txt public/
          cp Audiobooks.txt public/
          cp Abfrage_Quellen.txt public/

      - name: Push to public repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUBLIC_REPO_TOKEN }}
        with:
          source-directory: public
          destination-github-username: KhungFu
          destination-repository-name: kisilerim
          user-email: github-actions@github.com
          target-branch: main
