name: Sync selected files

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Prepare files
        run: |
          mkdir public
          cp https://github.com/KhungFu/nexus/blob/main/mentor_name.txt public/
          cp https://github.com/KhungFu/nexus/blob/main/toplam_egitim.txt public/
          cp https://github.com/KhungFu/nexus/blob/main/NewsVerlage.txt public/
          cp https://github.com/KhungFu/nexus/blob/main/Bot_egitim_videolari.txt public/
          cp https://github.com/KhungFu/nexus/blob/main/Audiobooks.txt public/
          cp https://github.com/KhungFu/nexus/blob/main/Abfrage_Quellen.txt public/
          
          
      - name: Push to public repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PUBLIC_REPO_TOKEN }}
        with:
          source-directory: public
          destination-github-username: KHungFu
          destination-repository-name: kisilerim
          user-email: bot@github.com
          target-branch: main
